In [ ]:
# %pip install -U scikit-learn
# %pip install -U umap-learn
# %pip install -U kaleido
# %pip install -U plotly
# !plotly_get_chrome
# %pip install -U nbformat jupyter ipywidgets

In [2]:
import pandas as pd
import plotly.express as px
from plotly.io import write_image
from sklearn.manifold import TSNE

In [ ]:
# dataset loading
df = pd.read_csv('all-results.csv', index_col=0, header=0).T

### t-SNE

In [4]:
for i, p in enumerate([3,5,10]): 
    # t-SNE fitting
    tsne = TSNE(n_components=2, perplexity=p,
                max_iter=int(1e6), random_state=0) 
    X_tsne = tsne.fit_transform(df)

    # t-SNE visualization DataFrame
    df_tsne = pd.DataFrame(X_tsne, columns=['x', 'y'])
    df_tsne['model'] = df.index
    df_tsne['acc'] = df.mean(axis=1).values

    fig = px.scatter(df_tsne, x='x', y='y', text='model', 
                    labels={'x': 'component 1', 'y': 'component 2'},
                    color='acc',
                    color_continuous_scale=px.colors.sequential.Viridis,
                    size='acc',
                    size_max=8,
                    opacity=0.7)
    # fig size
    fig.update_layout(width=800, height=400)
    # title
    fig.update_layout(title=f'Visualization of TSC models using t-SNE (perplexity={p}, metric=euclidean)', 
                        title_x=0.5,  # center the title
                        title_y=0.98,
                        title_font=dict(size=20))
    # tight layout
    fig.update_layout(
        coloraxis_colorbar=dict(
            title="avg.<br>acc",
            title_font=dict(size=13),
            tickmode="array",
            tickvals=list(range(70,80,2)),
            lenmode="fraction",
            thickness=20,
            len=1,
            yanchor="middle",
            y=0.5,
            xanchor="left",
            x=1.0,
        ),
    )
    fig.update_layout(margin=dict(l=0, r=0, t=30, b=15))
    fig.update_xaxes(title_standoff=7)
    fig.update_yaxes(title_standoff=7)

    # text size
    fig.update_traces(textfont_size=18)
    fig.update_traces(textposition='bottom center')
    fig.update_layout(showlegend=False)
    fig.show()

    # # save the figure
    # write_image(fig, f'figures_tmp/tsne_perplexity_{p}.pdf', width=800, height=400, scale=2, format='pdf')

In [5]:
for i, p in enumerate([3,5,10]): 
    # t-SNE fitting
    tsne = TSNE(n_components=2, perplexity=p, metric="correlation",
                max_iter=int(1e6), random_state=0) 
    X_tsne = tsne.fit_transform(df)

    # t-SNE visualization DataFrame
    df_tsne = pd.DataFrame(X_tsne, columns=['x', 'y'])
    df_tsne['model'] = df.index
    df_tsne['acc'] = df.mean(axis=1).values

    fig = px.scatter(df_tsne, x='x', y='y', text='model', 
                    labels={'x': 'component 1', 'y': 'component 2'},
                    color='acc',
                    color_continuous_scale=px.colors.sequential.Viridis,
                    size='acc',
                    size_max=8,
                    opacity=0.7)
    # fig size
    fig.update_layout(width=800, height=400)
    # title
    fig.update_layout(title=f'Visualization of TSC models using t-SNE (perplexity={p}, metric=correlation)', 
                        title_x=0.5,  # center the title
                        title_y=0.98,
                        title_font=dict(size=20))
    # tight layout
    fig.update_layout(
        coloraxis_colorbar=dict(
            title="avg.<br>acc",
            title_font=dict(size=13),
            tickmode="array",
            tickvals=list(range(70,80,2)),
            lenmode="fraction",
            thickness=20,
            len=1,
            yanchor="middle",
            y=0.5,
            xanchor="left",
            x=1.0,
        ),
    )
    fig.update_layout(margin=dict(l=0, r=0, t=30, b=15))
    fig.update_xaxes(title_standoff=7)
    fig.update_yaxes(title_standoff=7)

    # text size
    fig.update_traces(textfont_size=18)
    fig.update_traces(textposition='bottom center')
    fig.update_layout(showlegend=False)
    fig.show()

    # save the figure
    write_image(fig, f'figures_tmp/tsne_perplexity_{p}.pdf', width=800, height=400, scale=2, format='pdf')

In [6]:
# from plotly.subplots import make_subplots
# fig = make_subplots(rows=1, cols=3, subplot_titles=[f'perplexity = {p}' for p in [3,5,10]],
#                     horizontal_spacing = 0.05)

# for i, p in enumerate([3,5,10]): 
#     # t-SNE fitting
#     tsne = TSNE(n_components=2, perplexity=p, max_iter=int(1e6), random_state=0) 
#     X_tsne = tsne.fit_transform(df)

#     # t-SNE visualization DataFrame
#     df_tsne = pd.DataFrame(X_tsne, columns=['x', 'y'])
#     df_tsne['model'] = df.index
#     df_tsne['acc'] = df.mean(axis=1).values

#     fig.add_trace(
#         go.Scatter(
#             x=df_tsne['x'],
#             y=df_tsne['y'],
#             mode='markers+text',
#             text=df_tsne['model'],
#             textfont=dict(size=10),
#             textposition='bottom center',
#             marker=dict(
#                 size=df_tsne['acc']*0.1,
#                 color=df_tsne['acc'],
#                 colorscale='Viridis',
#                 showscale=(i==2),  # show color scale only for the last subplot
#                 colorbar=dict(title='accuracy') if i==2 else None,  # only for the last subplot
#                 opacity=0.7)
#         ),
#         row=1, col=i+1
#     )
    
# # fig size
# fig.update_layout(width=1600, height=400)
# # tight layout
# fig.update_layout(margin=dict(l=20, r=20, t=30, b=20))
# fig.update_xaxes(title_text='component 1')
# fig.update_yaxes(title_text='component 2')
# # Adjust y-axis title position for the first subplot
# fig.update_yaxes(title_standoff=0, row=1, col=1)
# fig.update_yaxes(title_standoff=0, row=1, col=2)
# fig.update_yaxes(title_standoff=0, row=1, col=3)

# # text size
# fig.update_traces(textfont_size=12)
# fig.update_traces(textposition='bottom center')
# fig.update_layout(showlegend=False)
# fig.show()

# # save the figure
# write_image(fig, f'figures_tmp/tsne_perplexity_3,5,10.pdf', width=1600, height=400, scale=2, format='pdf')

### UMAP

In [8]:
from umap import UMAP

for i, k in enumerate([3, 6, 9, 12, 15]):
    reduction = UMAP(n_components=2, n_neighbors=k, metric="correlation",
                     random_state=0, n_jobs=1)
    X_umap = reduction.fit_transform(df)
    df_umap = pd.DataFrame(X_umap, columns=['x', 'y'])
    df_umap['model'] = df.index
    df_umap['acc'] = df.mean(axis=1).values


    fig = px.scatter(df_umap, x='x', y='y', text='model', 
                    labels={'x': 'component 1', 'y': 'component 2'},
                    color='acc',
                    color_continuous_scale=px.colors.sequential.Viridis,
                    size='acc',
                    size_max=8,
                    opacity=0.7)
    # fig size
    fig.update_layout(width=800, height=400)
    # title
    fig.update_layout(title=f'Visualization of TSC models using UMAP (n_neighbors={k}, metric=correlation)', 
                        title_x=0.5,  # center the title
                        title_y=0.98,
                        title_font=dict(size=20))
    # tight layout
    fig.update_layout(
        coloraxis_colorbar=dict(
            title="avg.<br>acc",
            title_font=dict(size=13),
            tickmode="array",
            tickvals=list(range(70,80,2)),
            lenmode="fraction",
            thickness=20,
            len=1,
            yanchor="middle",
            y=0.5,
            xanchor="left",
            x=1.0,
        ),
    )
    fig.update_layout(margin=dict(l=0, r=0, t=30, b=15))
    fig.update_xaxes(title_standoff=7)
    fig.update_yaxes(title_standoff=7)

    # text size
    fig.update_traces(textfont_size=20)
    fig.update_traces(textposition='bottom center')
    fig.update_layout(showlegend=False)
    fig.show()

    # # save the figure
    write_image(fig, f'figures_tmp/umap_neighbors{k}.pdf', width=800, height=400, scale=2, format='pdf')

In [9]:
from umap import UMAP

for i, k in enumerate([3, 6, 9, 12, 15]):
    reduction = UMAP(n_components=2, n_neighbors=k, 
                     random_state=0, n_jobs=1)
    X_umap = reduction.fit_transform(df)
    df_umap = pd.DataFrame(X_umap, columns=['x', 'y'])
    df_umap['model'] = df.index
    df_umap['acc'] = df.mean(axis=1).values


    fig = px.scatter(df_umap, x='x', y='y', text='model', 
                    labels={'x': 'component 1', 'y': 'component 2'},
                    color='acc',
                    color_continuous_scale=px.colors.sequential.Viridis,
                    size='acc',
                    size_max=8,
                    opacity=0.7)
    # fig size
    fig.update_layout(width=800, height=400)
    # title
    fig.update_layout(title=f'Visualization of TSC models using UMAP (n_neighbors={k}, metric=euclidean)', 
                        title_x=0.5,  # center the title
                        title_y=0.98,
                        title_font=dict(size=20))
    # tight layout
    fig.update_layout(
        coloraxis_colorbar=dict(
            title="avg.<br>acc",
            title_font=dict(size=13),
            tickmode="array",
            tickvals=list(range(70,80,2)),
            lenmode="fraction",
            thickness=20,
            len=1,
            yanchor="middle",
            y=0.5,
            xanchor="left",
            x=1.0,
        ),
    )
    fig.update_layout(margin=dict(l=0, r=0, t=30, b=15))
    fig.update_xaxes(title_standoff=7)
    fig.update_yaxes(title_standoff=7)

    # text size
    fig.update_traces(textfont_size=18)
    fig.update_traces(textposition='bottom center')
    fig.update_layout(showlegend=False)
    fig.show()

    # # # save the figure
    # write_image(fig, f'figures_tmp/umap_neighbors{k}.pdf', width=800, height=400, scale=2, format='pdf')

### ACC

In [10]:
df = df.copy()  # select first 20 models for visualization
df['categories'] = [
    'Non-DL', 'Non-DL', 'Non-DL', 'Non-DL', 'Non-DL',
    'MLP-based', 'MLP-based', 'MLP-based', 
    'CNN-based', 'CNN-based', 'CNN-based', 'CNN-based',
    'Transformer-based', 'Transformer-based', 'Transformer-based', 'Transformer-based', 'Transformer-based', 'Transformer-based',
    'Shaplet+CNN', 'Mamba-based', 'Mamba-based'
]

In [11]:
import plotly.graph_objects as go

color_map = {
    "Non-DL": "#B0B0B0",            # 회색
    "MLP-based": "#7D68B1",           # 오렌지
    "CNN-based": "#D5B85B",          # 스카이 블루
    "Transformer-based": "#2C5AA0",  # 다크 블루
    "Shaplet+CNN": "#5BB3C5",        # 청록
    "Mamba-based": "#F2A900",        # 노랑
}



# 메달 이모지
medals = ["🥇", "🥈", "🥉"]

# subplot 그리기
from plotly.subplots import make_subplots

fig = make_subplots(rows=1, cols=1)

for i, c in enumerate(df['categories'].unique()):
    df_subset = df[df['categories'] == c].copy()
    fig.add_trace(
            go.Bar(
                x=df_subset.index,
                y=df_subset.iloc[:, :10].mean(axis=1),
                marker_color=[color_map[c] for c in df_subset['categories']],
                marker_pattern_shape=['x'] * len(df_subset),
                text=[f"{v:.1f}" for v in df_subset.iloc[:, :10].mean(axis=1)],
                textposition="outside",
                hovertext=[f"<b>{df_subset.index[i]}</b><br>{c} <br>{df_subset.iloc[i, :10].mean():.2f}" for i in range(len(df_subset))],
                hoverinfo="text",
                name="10 dataset\n(EC-UW)",
                legendgroup=c,
                legendgrouptitle_text=c,
                
            )
    )
    fig.add_trace(
            go.Bar(
                x=df_subset.index,
                y=df_subset.iloc[:, :-1].mean(axis=1),
                marker_color=[color_map[c] for c in df_subset['categories']],
                text=[f"{v:.1f}" for v in df_subset.iloc[:, :-1].mean(axis=1)],
                textposition="outside",
                hovertext=[f"<b>{df_subset.index[i]}</b><br>{c} <br>{df_subset.iloc[i, :-1].mean():.2f}" for i in range(len(df_subset))],
                hoverinfo="text",
                name="all dataset",
                legendgroup=c,
                
            )
    )


fig.update_traces(
    marker=dict(line_color="grey", pattern_fillmode="replace"),
    # marker_color=df_subset['categories'].iloc[::2].map(color_map),
    texttemplate='%{text:.1f}',
    textposition='outside',
    hovertemplate='<b>%{x}</b><br>Category: %{marker.color}<br>Accuracy: %{y:.2f}<extra></extra>',
)

fig.update_layout(
    height=700,
    width=1200,
    title_text="Classification Performance of TSC Models",
    barmode="group",
    margin=dict(l=20, r=20, t=30, b=30),
    title_x=0.5,  # center the title
    title_font=dict(size=16),
    xaxis=dict(
        tickmode='array',
        tickvals=list(range(len(df.index))),
        ticktext=df.index,
        tickangle=-45,
        title_font=dict(size=14)
    ),
    yaxis_title="average accuracy (%)",
    legend=dict(
        title_text="Categories",
        title_font=dict(size=14),
        font=dict(size=12),
        orientation="h",
    ),
)

fig.update_yaxes(showticklabels=False, range=[66, 81])  # y축 범위 설정
fig.show()

# save the figure
write_image(fig, f'figures_tmp/legend.pdf', scale=2, format='pdf', width=1200, height=700)

In [12]:
# subplot 그리기
from plotly.subplots import make_subplots

fig = make_subplots(rows=1, cols=1)
df_pivot = []
for i, c in enumerate(df['categories'].unique()):
    for model in df[df['categories'] == c].index:
        # print(model)
        df_pivot.append({
            'categories': c,
            'model': model,
            'acctype': 'all dataset',
            'acc': df.loc[model].iloc[:-1].mean(),
        })
        df_pivot.append({
            'categories': c,
            'model': model,
            'acctype': '10 dataset',
            'acc': df.loc[model].iloc[:10].mean(),
        })
df_pivot = pd.DataFrame(df_pivot)

df_pivot.head()

  categories   model      acctype        acc
0     Non-DL   DTW_D  all dataset  68.019691
1     Non-DL   DTW_D   10 dataset  70.354467
2     Non-DL  ROCKET  all dataset  73.305689
3     Non-DL  ROCKET   10 dataset  74.368405
4     Non-DL     HC2  all dataset  76.865881

In [13]:
# 색상 매핑
color_map = {
    "Non-DL": "#B0B0B0",            # 회색
    "MLP-based": "#7D68B1",           # 오렌지
    "CNN-based": "#D5B85B",          # 스카이 블루
    "Transformer-based": "#2C5AA0",  # 다크 블루
    "Shaplet+CNN": "#5BB3C5",        # 청록
    "Mamba-based": "#F2A900",        # 노랑
}


# 메달 이모지
medals = ["🥇", "🥈", "🥉"]


fig = px.bar(df_pivot, x='model', y='acc', 
             pattern_shape='acctype',
             pattern_shape_sequence=['x', ''],
             text='acc',
             text_auto='.2f',
             category_orders={'model': df_pivot['model'].unique(), 'acctype': ['10 dataset', 'all dataset', ]},
             custom_data=['categories'],
             )

fig.update_traces(
    marker=dict(line_color="grey", pattern_fillmode="replace"),
    marker_color=df_pivot['categories'].iloc[::2].map(color_map),
    texttemplate='%{text:.1f}',
    textposition='outside',
    textfont=dict(size=10),
    hovertemplate='<b>%{x}</b><br>Category: %{customdata[0]}<br>Accuracy: %{y:.6f}<extra></extra>',
)
# update names
fig.for_each_trace(
    lambda t: t.update(name=t.name.replace('10 dataset', '10 dataset\n(EC-UW)').replace('all dataset', 'all dataset')) 
    if t.name in ['10 dataset', 'all dataset'] else t
)



# add medal emojis to the top of the bars
top3 = df_pivot[(df_pivot['acctype'] == 'all dataset')].nlargest(3, 'acc')
for i, (j, row) in enumerate(top3.iterrows()):
    # find x position of the bar
    x_pos = df_pivot[df_pivot['model'] == row['model']].index[0] // 2
    fig.add_annotation(
        x=x_pos + 0.2,
        y=row['acc'] + 1.6,  # Adjust the y position to place the emoji above the bar
        text=medals[i],
        showarrow=False,
        font=dict(size=20, family="Noto Color Emoji"),  # Adjust the size of the emoji
        align='center',
        bgcolor='rgba(0,0,0,0)',  # Transparent background
    )

top3_10 = df_pivot[(df_pivot['acctype'] == '10 dataset')].nlargest(3, 'acc')
for i, (j, row) in enumerate(top3_10.iterrows()):
    # find x position of the bar
    x_pos = df_pivot[df_pivot['model'] == row['model']].index[0] // 2
    fig.add_annotation(
        x=x_pos - 0.2,
        y=row['acc'] + 1.6,  # Adjust the y position to place the emoji above the bar
        text=medals[i],
        showarrow=False,
        font=dict(size=20, family="Noto Color Emoji"),  # Adjust the size of the emoji
        align='center',
        bgcolor='rgba(0,0,0,0)',  # Transparent background
    )






fig.update_layout(
    # template="plotly_white",
    paper_bgcolor='rgba(0,0,0,0)',  # 투명 배경
    plot_bgcolor="#E8ECF1",  # 연한 회색 배경
    height=400,
    width=1200,
    barmode='group',
    bargap=0.2,  # 바 간격 조절
    bargroupgap=0.0,  # 그룹 간격 조절
    # title_text="Classification Performance of TSC Models",
    margin=dict(l=20, r=20, t=30, b=10),
    title_x=0.5,  # center the title
    title_font=dict(size=16),
    yaxis_title="average accuracy (%)",
    # legend=dict(
    #     title_text="Categories",
    #     title_font=dict(size=14),
    #     font=dict(size=12)
    # ),
    showlegend=False,  # Hide legend
)
fig.update_xaxes(
    title_text="",
    tickangle=-30,
    tickfont=dict(size=15)
)
fig.update_yaxes(showticklabels=False, range=[66, 81.5])  # y축 범위 설정
fig.show()

# save the figure
write_image(fig, f'figures_tmp/barplot (acc).pdf', scale=2, format='pdf', width=1200, height=400)

In [14]:
# 색상 매핑
color_map = {
    "Non-DL": "#B0B0B0",            # 회색
    "MLP-based": "#7D68B1",           # 오렌지
    "CNN-based": "#D5B85B",          # 스카이 블루
    "Transformer-based": "#2C5AA0",  # 다크 블루
    "Shaplet+CNN": "#5BB3C5",        # 노랑
    # "Mamba-based": "#AC6168",          # 청록
    "Mamba-based": "#F2A900",        # 노랑
    # "Ours": "#F2A900",        # 노랑
}


# 메달 이모지
medals = ["🥇", "🥈", "🥉"]


fig = px.bar(df_pivot, x='model', y='acc', 
             pattern_shape='acctype',
             pattern_shape_sequence=['x', ''],
             text='acc',
             text_auto='.2f',
             category_orders={'model': df_pivot['model'].unique(), 'acctype': ['10 dataset', 'all dataset', ]},
             custom_data=['categories'],
             )

fig.update_traces(
    marker=dict(line_color="grey", pattern_fillmode="replace"),
    marker_color=df_pivot['categories'].iloc[::2].map(color_map),
    texttemplate='%{text:.2f}',
    textposition='inside',
    textfont=dict(size=30),
    hovertemplate='<b>%{x}</b><br>Category: %{customdata[0]}<br>Accuracy: %{y:.6f}<extra></extra>',
)
# update names
fig.for_each_trace(
    lambda t: t.update(name=t.name.replace('10 dataset', '10 dataset\n(EC-UW)').replace('all dataset', 'all dataset')) 
    if t.name in ['10 dataset', 'all dataset'] else t
)



# add medal emojis to the top of the bars
top3 = df_pivot[(df_pivot['acctype'] == 'all dataset')].nlargest(3, 'acc')
for i, (j, row) in enumerate(top3.iterrows()):
    # find x position of the bar
    x_pos = df_pivot[df_pivot['model'] == row['model']].index[0] // 2
    fig.add_annotation(
        x=x_pos + 0.22,
        y=row['acc'] + 1.6,  # Adjust the y position to place the emoji above the bar
        text=medals[i],
        showarrow=False,
        font=dict(size=22, family="Noto Color Emoji"),  # Adjust the size of the emoji
        align='center',
        bgcolor='rgba(0,0,0,0)',  # Transparent background
    )

top3_10 = df_pivot[(df_pivot['acctype'] == '10 dataset')].nlargest(3, 'acc')
for i, (j, row) in enumerate(top3_10.iterrows()):
    # find x position of the bar
    x_pos = df_pivot[df_pivot['model'] == row['model']].index[0] // 2
    fig.add_annotation(
        x=x_pos - 0.22,
        y=row['acc'] + 1.6,  # Adjust the y position to place the emoji above the bar
        text=medals[i],
        showarrow=False,
        font=dict(size=22, family="Noto Color Emoji"),  # Adjust the size of the emoji
        align='center',
        bgcolor='rgba(0,0,0,0)',  # Transparent background
    )



fig.update_layout(
    # template="plotly_white",
    paper_bgcolor='rgba(0,0,0,0)',  # 투명 배경
    plot_bgcolor="#E8ECF1",  # 연한 회색 배경
    height=350,
    width=1200,
    barmode='group',
    bargap=0.15,  # 바 간격 조절
    bargroupgap=0.0,  # 그룹 간격 조절
    # title_text="Classification Performance of TSC Models",
    margin=dict(l=20, r=20, t=30, b=10),
    title_x=0.5,  # center the title
    title_font=dict(size=16),
    yaxis_title="average accuracy (%)",
    # legend=dict(
    #     title_text="Categories",
    #     title_font=dict(size=14),
    #     font=dict(size=12)
    # ),
    showlegend=False,  # Hide legend
)
fig.update_xaxes(
    title_text="",
    tickangle=-30,
    tickfont=dict(size=15)
)
fig.update_yaxes(showticklabels=False, range=[64, 82], 
                 tickvals=list(range(65,82,5)),
                 title_font=dict(size=16))
fig.show()

# save the figure
write_image(fig, f'figures_tmp/barplot (acc).pdf', scale=2, format='pdf', width=1200, height=350)

In [15]:
# 색상 매핑
color_map = {
    "Non-DL": "#B0B0B0",            # 회색
    "MLP-based": "#7D68B1",           # 오렌지
    "CNN-based": "#D5B85B",          # 스카이 블루
    "Transformer-based": "#2C5AA0",  # 다크 블루
    "Shaplet+CNN": "#5BB3C5",        # 노랑
    # "Mamba-based": "#AC6168",          # 청록
    "Mamba-based": "#F2A900",        # 노랑
    # "Ours": "#F2A900",        # 노랑
}


# 메달 이모지
medals = ["🥇", "🥈", "🥉"]


fig = px.bar(df_pivot[df_pivot['acctype'] == 'all dataset'], x='model', y='acc', 
             text='acc',
             text_auto='.2f',
             category_orders={'model': df_pivot['model'].unique()},
             custom_data=['categories'],
             )

fig.update_traces(
    marker=dict(line_color="grey", pattern_fillmode="replace"),
    marker_color=df_pivot['categories'].iloc[::2].map(color_map),
    texttemplate='%{text:.2f}',
    textposition='inside',
    hovertemplate='<b>%{x}</b><br>Category: %{customdata[0]}<br>Accuracy: %{y:.6f}<extra></extra>',
)



# add medal emojis to the top of the bars
top3 = df_pivot[(df_pivot['acctype'] == 'all dataset')].nlargest(3, 'acc')
for i, (j, row) in enumerate(top3.iterrows()):
    # find x position of the bar
    x_pos = df_pivot[df_pivot['model'] == row['model']].index[0] // 2
    fig.add_annotation(
        x=x_pos,
        y=row['acc'] + 1.2,  # Adjust the y position to place the emoji above the bar
        text=medals[i],
        showarrow=False,
        font=dict(size=25, family="Noto Color Emoji"),  # Adjust the size of the emoji
        align='center',
        bgcolor='rgba(0,0,0,0)',  # Transparent background
    )







fig.update_layout(
    # template="plotly_white",
    paper_bgcolor='rgba(0,0,0,0)',  # 투명 배경
    plot_bgcolor="#E8ECF1",  # 연한 회색 배경
    height=350,
    width=1200,
    barmode='group',
    bargap=0.1,  # 바 간격 조절
    bargroupgap=0.0,  # 그룹 간격 조절
    # title_text="Classification Performance of TSC Models",
    margin=dict(l=20, r=20, t=30, b=10),
    title_x=0.5,  # center the title
    title_font=dict(size=16),
    yaxis_title="average accuracy (%)",
    # legend=dict(
    #     title_text="Categories",
    #     title_font=dict(size=14),
    #     font=dict(size=12)
    # ),
    showlegend=False,  # Hide legend
    # font=dict(size=15)
)
fig.update_xaxes(
    title_text="",
    tickangle=-30,
    tickfont=dict(size=15)
)
fig.update_yaxes(showticklabels=False, range=[66, 82], 
                 tickvals=list(range(66,82,2)),)
fig.show()

# # save the figure
# write_image(fig, f'figures_tmp/barplot (acc).pdf', scale=2, format='pdf', width=1200, height=350)

### Rank

In [16]:
# dataset loading
df_rank = df.rank(axis=0, method='min',ascending=False).astype(int)
df_rank.head()

,EC,FD,HW,HB,JV,PEMS,SRS1,SRS2,SAD,UW,...,IW,LIB,LSST,MI,NATO,PD,PS,RS,SWJ,categories
DTW_D,12,21,3,21,19,21,20,21,19,9,...,18,18,8,20,20,16,10,20,21,8
ROCKET,4,17,4,19,21,17,18,18,10,4,...,19,10,4,17,18,14,6,6,18,8
HC2,3,18,7,9,7,2,15,20,11,4,...,9,3,2,20,16,17,4,8,19,8
Hydra,2,20,6,17,14,1,17,13,11,2,...,8,4,1,17,17,15,2,3,19,8
MR+Hydra,1,19,8,16,7,18,1,19,13,4,...,11,4,3,19,13,18,1,8,11,8

In [17]:
df_rank['categories'] = [
    'Non-DL', 'Non-DL', 'Non-DL', 'Non-DL', 'Non-DL',
    'MLP-based', 'MLP-based', 'MLP-based', 
    'CNN-based', 'CNN-based', 'CNN-based', 'CNN-based',
    'Transformer-based', 'Transformer-based', 'Transformer-based', 'Transformer-based', 'Transformer-based', 'Transformer-based',
    'Shaplet+CNN', 'Mamba-based', 'Mamba-based',
]
df_rank = df_rank.copy()  # select first 20 models for visualization

In [18]:
import plotly.graph_objects as go
import numpy as np

# subplot 그리기
from plotly.subplots import make_subplots

fig = make_subplots(rows=1, cols=1)
df_rank_pivot = []
for i, c in enumerate(df_rank['categories'].unique()):
    for model in df_rank[df_rank['categories'] == c].index:
        # print(model)
        df_rank_pivot.append({
            'categories': c,
            'model': model,
            'ranktype': 'all dataset',
            'rank': df_rank.loc[model].iloc[:-1].mean(),
        })
        df_rank_pivot.append({
            'categories': c,
            'model': model,
            'ranktype': '10 dataset',
            'rank': df_rank.loc[model].iloc[:10].mean(),
        })
df_rank_pivot = pd.DataFrame(df_rank_pivot)

df_rank_pivot.head()

  categories   model     ranktype       rank
0     Non-DL   DTW_D  all dataset  16.033333
1     Non-DL   DTW_D   10 dataset  16.600000
2     Non-DL  ROCKET  all dataset  11.200000
3     Non-DL  ROCKET   10 dataset  13.200000
4     Non-DL     HC2  all dataset   8.900000

In [19]:
# 색상 매핑
color_map = {
    "Non-DL": "#B0B0B0",            # 회색
    "MLP-based": "#7D68B1",           # 오렌지
    "CNN-based": "#D5B85B",          # 스카이 블루
    "Transformer-based": "#2C5AA0",  # 다크 블루
    "Shaplet+CNN": "#5BB3C5",        # 노랑
    # "Mamba-based": "#AC6168",          # 청록
    "Mamba-based": "#F2A900",        # 노랑
    # "Ours": "#F2A900",        # 노랑
}


# 메달 이모지
medals = ["🥇", "🥈", "🥉"]


fig = px.bar(df_rank_pivot, x='model', y='rank', 
             pattern_shape='ranktype',
             pattern_shape_sequence=['x', ''],
             text='rank',
             text_auto='.2f',
             category_orders={'model': df_rank_pivot['model'].unique(), 'ranktype': ['10 dataset', 'all dataset', ]},
             custom_data=['categories'],
             )

fig.update_traces(
    marker=dict(line_color="grey", pattern_fillmode="replace"),
    marker_color=df_rank_pivot['categories'].iloc[::2].map(color_map),
    texttemplate='%{text:.1f}',
    textposition='outside',
    hovertemplate='<b>%{x}</b><br>Category: %{customdata[0]}<br>rankuracy: %{y:.6f}<extra></extra>',
)
# update names
fig.for_each_trace(
    lambda t: t.update(name=t.name.replace('10 dataset', '10 dataset\n(EC-UW)').replace('all dataset', 'all dataset')) 
    if t.name in ['10 dataset', 'all dataset'] else t
)


# add medal emojis to the top of the bars
top3 = df_rank_pivot[(df_rank_pivot['ranktype'] == 'all dataset')].nsmallest(3, 'rank')
for i, (j, row) in enumerate(top3.iterrows()):
    # find x position of the bar
    x_pos = df_rank_pivot[df_rank_pivot['model'] == row['model']].index[0] // 2
    fig.add_annotation(
        x=x_pos + 0.2,
        y=row['rank'] + 1.7,  # Adjust the y position to place the emoji above the bar
        text=medals[i],
        showarrow=False,
        font=dict(size=20, family="Noto Color Emoji"),  # Adjust the size of the emoji
        align='center',
        bgcolor='rgba(0,0,0,0)',  # Transparent background
    )

top3_10 = df_rank_pivot[(df_rank_pivot['ranktype'] == '10 dataset')].nsmallest(3, 'rank')
for i, (j, row) in enumerate(top3_10.iterrows()):
    # find x position of the bar
    x_pos = df_rank_pivot[df_rank_pivot['model'] == row['model']].index[0] // 2
    fig.add_annotation(
        x=x_pos - 0.2,
        y=row['rank'] + 1.7,  # Adjust the y position to place the emoji above the bar
        text=medals[i],
        showarrow=False,
        font=dict(size=20, family="Noto Color Emoji"),  # Adjust the size of the emoji
        align='center',
        bgcolor='rgba(0,0,0,0)',  # Transparent background
    )






fig.update_layout(
    # template="plotly_white",
    paper_bgcolor='rgba(0,0,0,0)',  # 투명 배경
    plot_bgcolor="#E8ECF1",  # 연한 회색 배경
    height=400,
    width=1200,
    barmode='group',
    bargap=0.2,  # 바 간격 조절
    bargroupgap=0.0,  # 그룹 간격 조절
    # title_text="Classification Performance of TSC Models",
    margin=dict(l=20, r=20, t=30, b=10),
    title_x=0.5,  # center the title
    title_font=dict(size=16),
    yaxis_title="average rank",
    # legend=dict(
    #     title_text="Categories",
    #     title_font=dict(size=14),
    #     font=dict(size=12)
    # ),
    showlegend=False
)
fig.update_xaxes(
    title_text="",
    tickangle=-30,
    tickfont=dict(size=15)
)
fig.update_yaxes(showticklabels=False, range=[3, 18],
                 title_font=dict(size=16))  # y축 범위 설정
fig.show()

# # save the figure
# write_image(fig, f'figures_tmp/barplot (rank).pdf', scale=2, format='pdf', width=1200, height=400)

In [20]:
# 색상 매핑
color_map = {
    "Non-DL": "#B0B0B0",            # 회색
    "MLP-based": "#7D68B1",           # 오렌지
    "CNN-based": "#D5B85B",          # 스카이 블루
    "Transformer-based": "#2C5AA0",  # 다크 블루
    "Shaplet+CNN": "#5BB3C5",        # 노랑
    # "Mamba-based": "#AC6168",          # 청록
    "Mamba-based": "#F2A900",        # 노랑
    # "Ours": "#F2A900",        # 노랑
}


# 메달 이모지
medals = ["🥇", "🥈", "🥉"]


fig = px.bar(df_rank_pivot, x='model', y='rank', 
             pattern_shape='ranktype',
             pattern_shape_sequence=['x', ''],
             text='rank',
             text_auto='.2f',
             category_orders={'model': df_rank_pivot['model'].unique(), 'ranktype': ['10 dataset', 'all dataset', ]},
             custom_data=['categories'],
             )

fig.update_traces(
    marker=dict(line_color="grey", pattern_fillmode="replace"),
    marker_color=df_rank_pivot['categories'].iloc[::2].map(color_map),
    texttemplate='%{text:.1f}',
    textposition='inside',
    textfont=dict(size=30),
    hovertemplate='<b>%{x}</b><br>Category: %{customdata[0]}<br>rankuracy: %{y:.6f}<extra></extra>',
)
# update names
fig.for_each_trace(
    lambda t: t.update(name=t.name.replace('10 dataset', '10 dataset\n(EC-UW)').replace('all dataset', 'all dataset')) 
    if t.name in ['10 dataset', 'all dataset'] else t
)


# add medal emojis to the top of the bars
top3 = df_rank_pivot[(df_rank_pivot['ranktype'] == 'all dataset')].nsmallest(3, 'rank')
for i, (j, row) in enumerate(top3.iterrows()):
    # find x position of the bar
    x_pos = df_rank_pivot[df_rank_pivot['model'] == row['model']].index[0] // 2
    fig.add_annotation(
        x=x_pos + 0.22,
        y=row['rank'] + 1.2,  # Adjust the y position to place the emoji above the bar
        text=medals[i],
        showarrow=False,
        font=dict(size=22, family="Noto Color Emoji"),  # Adjust the size of the emoji
        align='center',
        bgcolor='rgba(0,0,0,0)',  # Transparent background
    )

top3_10 = df_rank_pivot[(df_rank_pivot['ranktype'] == '10 dataset')].nsmallest(3, 'rank')
for i, (j, row) in enumerate(top3_10.iterrows()):
    # find x position of the bar
    x_pos = df_rank_pivot[df_rank_pivot['model'] == row['model']].index[0] // 2
    fig.add_annotation(
        x=x_pos - 0.22,
        y=row['rank'] + 1.2,  # Adjust the y position to place the emoji above the bar
        text=medals[i],
        showarrow=False,
        font=dict(size=22, family="Noto Color Emoji"),  # Adjust the size of the emoji
        align='center',
        bgcolor='rgba(0,0,0,0)',  # Transparent background
    )






fig.update_layout(
    # template="plotly_white",
    paper_bgcolor='rgba(0,0,0,0)',  # 투명 배경
    plot_bgcolor="#E8ECF1",  # 연한 회색 배경
    height=350,
    width=1200,
    barmode='group',
    bargap=0.15,  # 바 간격 조절
    bargroupgap=0.0,  # 그룹 간격 조절
    # title_text="Classification Performance of TSC Models",
    margin=dict(l=20, r=20, t=30, b=10),
    title_x=0.5,  # center the title
    title_font=dict(size=16),
    yaxis_title="average rank",
    # legend=dict(
    #     title_text="Categories",
    #     title_font=dict(size=14),
    #     font=dict(size=12)
    # ),
    showlegend=False
)
fig.update_xaxes(
    title_text="",
    tickangle=-30,
    tickfont=dict(size=16)
)
fig.update_yaxes(showticklabels=False, range=[3, 18],
                 title_font=dict(size=16))  # y축 범위 설정
fig.show()

# save the figure
write_image(fig, f'figures_tmp/barplot (rank).pdf', scale=2, format='pdf', width=1200, height=350)

In [21]:
# 색상 매핑
color_map = {
    "Non-DL": "#B0B0B0",            # 회색
    "MLP-based": "#7D68B1",           # 오렌지
    "CNN-based": "#D5B85B",          # 스카이 블루
    "Transformer-based": "#2C5AA0",  # 다크 블루
    "Shaplet+CNN": "#5BB3C5",        # 노랑
    # "Mamba-based": "#AC6168",          # 청록
    "Mamba-based": "#F2A900",        # 노랑
    # "Ours": "#F2A900",        # 노랑
}


# 메달 이모지
medals = ["🥇", "🥈", "🥉"]


fig = px.bar(df_rank_pivot[df_rank_pivot['ranktype'] == 'all dataset'], x='model', y='rank', 
             text='rank',
             text_auto='.2f',
             category_orders={'model': df_rank_pivot['model'].unique()},
             custom_data=['categories'],
             )

fig.update_traces(
    marker=dict(line_color="grey", pattern_fillmode="replace"),
    marker_color=df_rank_pivot['categories'].iloc[::2].map(color_map),
    texttemplate='%{text:.2f}',
    textposition='inside',
    hovertemplate='<b>%{x}</b><br>Category: %{customdata[0]}<br>Rank: %{y:.6f}<extra></extra>',
)



# add medal emojis to the top of the bars
top3 = df_rank_pivot[(df_rank_pivot['ranktype'] == 'all dataset')].nsmallest(3, 'rank')
for i, (j, row) in enumerate(top3.iterrows()):
    # find x position of the bar
    x_pos = df_rank_pivot[df_rank_pivot['model'] == row['model']].index[0] // 2
    fig.add_annotation(
        x=x_pos,
        y=row['rank'] + 1.2,  # Adjust the y position to place the emoji above the bar
        text=medals[i],
        showarrow=False,
        font=dict(size=25, family="Noto Color Emoji"),  # Adjust the size of the emoji
        align='center',
        bgcolor='rgba(0,0,0,0)',  # Transparent background
    )







fig.update_layout(
    # template="plotly_white",
    paper_bgcolor='rgba(0,0,0,0)',  # 투명 배경
    plot_bgcolor="#E8ECF1",  # 연한 회색 배경
    height=350,
    width=1200,
    barmode='group',
    bargap=0.1,  # 바 간격 조절
    bargroupgap=0.0,  # 그룹 간격 조절
    # title_text="Classification Performance of TSC Models",
    margin=dict(l=20, r=20, t=30, b=10),
    title_x=0.5,  # center the title
    title_font=dict(size=16),
    yaxis_title="average rank",
    # legend=dict(
    #     title_text="Categories",
    #     title_font=dict(size=14),
    #     font=dict(size=12)
    # ),
    showlegend=False,  # Hide legend
    # font=dict(size=15)
)
fig.update_xaxes(
    title_text="",
    tickangle=-30,
    tickfont=dict(size=15)
)
fig.update_yaxes(showticklabels=False, range=[3,18], 
                 tickvals=list(range(3,19,2)),)
fig.show()

# # save the figure
# write_image(fig, f'figures_tmp/barplot (rank).pdf', scale=2, format='pdf', width=1200, height=350)