In [23]:
import numpy as np
import pandas as pd
pd.set_option('display.float_format', lambda x: '%.13f' % x)
pd.set_option('display.max_columns', None)

from scipy.stats import wilcoxon

In [24]:
df = pd.read_excel('trainlossonly-result.xlsx', index_col=0)
df.head()

,CIF (HC2),DrCIF (HC2),HC2 (HC2),MiniRocket (BORF),DrCIF (BORF),MR+Hydra (BORF),MambaSL (trainlossonly),DTW_D,ROCKET,HC2,Hydra,MR+Hydra,DLinear,LightTS,MTS-Mixer,TimesNet,ModernTCN,TSLANet,TimeMixer++,FEDformer,ETSformer,Crossformer,PatchTST,GPT4TS,iTransformer,InterpGN,TSCMamba,MambaSL
EC,73.3840304182510,69.2015209125475,77.1863117870723,48.2889733840304,63.1178707224335,58.9353612167300,39.1634980988593,32.3193916349810,44.4866920152091,52.8517110266160,54.3726235741445,60.0760456273764,31.1787072243346,32.3193916349810,30.7984790874525,33.4600760456274,32.3193916349810,31.9391634980989,34.6007604562738,33.8403041825095,33.0798479087452,43.3460076045627,32.6996197718631,32.3193916349810,31.9391634980989,28.8973384030418,30.7984790874525,42.5855513307985
FD,62.7128263337117,62.0034052213394,66.0329171396141,58.2009080590238,59.1089670828604,61.8898978433598,68.3314415437004,52.8660612939841,61.6061293984109,61.3791146424518,60.9818388195233,61.2939841089671,69.4948921679909,68.4733257661748,68.5300794551646,70.1475595913734,66.9977298524404,66.9693530079455,69.6651532349603,69.8921679909194,68.3314415437004,69.6367763904654,68.0760499432463,68.6152099886493,68.4165720771850,63.7911464245176,70.2043132803632,69.2962542565267
HW,35.6470588235294,34.5882352941177,54.8235294117647,51.7647058823529,36.2352941176471,51.4117647058824,59.2941176470588,60.7058823529412,59.2941176470588,56.0000000000000,56.3529411764706,53.5294117647059,23.7647058823529,25.0588235294118,19.6470588235294,37.5294117647059,30.1176470588235,62.0000000000000,33.6470588235294,33.4117647058824,35.6470588235294,30.3529411764706,29.5294117647059,34.1176470588235,31.2941176470588,58.7058823529412,45.0588235294118,60.8235294117647
HB,78.0487804878049,79.0243902439024,73.1707317073171,74.1463414634146,79.0243902439024,73.1707317073171,76.5853658536585,71.7073170731707,75.6097560975610,78.5365853658537,76.5853658536585,77.0731707317073,76.5853658536585,77.5609756097561,79.0243902439024,83.9024390243902,78.0487804878049,79.5121951219512,80.4878048780488,78.0487804878049,78.5365853658537,79.0243902439024,73.6585365853659,79.0243902439024,78.0487804878049,80.4878048780488,78.5365853658537,80.4878048780488
JV,NaN,NaN,NaN,99.1891891891892,97.2972972972973,97.8378378378378,98.6486486486486,95.9459459459459,83.7837837837838,98.3783783783784,97.8378378378378,98.3783783783784,96.4864864864865,96.7567567567568,95.9459459459459,98.6486486486486,98.6486486486486,98.9189189189189,99.1891891891892,97.5675675675676,98.3783783783784,98.3783783783784,97.0270270270270,98.1081081081081,98.1081081081081,99.7297297297297,98.3783783783784,98.6486486486486

In [26]:
df_norm = ((df.T - df.iloc[:,7:].mean(axis=1)) / df.iloc[:,7:].std(axis=1)).T
wilcoxon_res = list()
for c in ['CIF (HC2)', 'DrCIF (HC2)', 'HC2 (HC2)',
          'MiniRocket (BORF)', 'DrCIF (BORF)', 'MR+Hydra (BORF)', 
          'MR+Hydra', 'HC2', 'Hydra']:

    valid_df = df_norm[['MambaSL (trainlossonly)', c]].dropna()
    res = wilcoxon((valid_df['MambaSL (trainlossonly)'] - valid_df[c]), alternative='greater')
    wilcoxon_res.append((c, res.pvalue))

df_wilcoxon = pd.DataFrame(wilcoxon_res, columns=['Classifier', 'p-value']).set_index('Classifier')
df_wilcoxon.T

Classifier,CIF (HC2),DrCIF (HC2),HC2 (HC2),MiniRocket (BORF),DrCIF (BORF),MR+Hydra (BORF),MR+Hydra,HC2,Hydra
p-value,0.0807566592338,0.0871051381981,0.1728753504474,0.0463086707470,0.0722046837993,0.0824077352270,0.2213554063831,0.3069462567189,0.2401207713597