In [1]:
import numpy as np
import pandas as pd
pd.set_option('display.float_format', lambda x: '%.13f' % x)
pd.set_option('display.max_columns', None)

from scipy.stats import wilcoxon

In [2]:
df = pd.read_excel('all-depth-ablation.xlsx', index_col=0)
df.head()

       1 (proposed)                2                3
EC 42.5855513307980 41.0646387832700 41.8250950570340
FD 69.2962542565270 68.7854710556190 69.0976163450620
HW 60.8235294117650 65.7647058823530 66.3529411764710
HB 80.4878048780490 80.4878048780490 80.4878048780490
JV 98.6486486486490 98.6486486486490 98.3783783783780

In [ ]:
df_norm = ((df.T - df.mean(axis=1)) / df.std(axis=1)).T
df_norm.fillna(0, inplace=True)
wilcoxon_res = list()
for c in df.columns:
    if c == '1 (proposed)':
        continue
    res = wilcoxon((df_norm['1 (proposed)'] - df_norm[c]), alternative='greater')
    wilcoxon_res.append((c, res.pvalue))

df_wilcoxon = pd.DataFrame(wilcoxon_res, columns=['Classifier', 'p-value']).set_index('Classifier')
df_wilcoxon.T

Classifier               2               3
p-value    0.0221042192623 0.0337319180658

In [4]:
df_rank = df.rank(axis=1, method='min',ascending=False).astype(int)
df_rank.head()

    1 (proposed)  2  3
EC             1  3  2
FD             1  3  2
HW             3  2  1
HB             1  1  1
JV             1  1  3