In [1]:
import torch, gc
gc.collect()
torch.cuda.empty_cache()

In [2]:
import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import itertools

def make_combination(config_dict):
    keys, values = zip(*config_dict.items())
    return [dict(zip(keys, v)) for v in itertools.product(*values)]

In [3]:
from omegaconf import OmegaConf
data_info = OmegaConf.load(f"../data_classification.yaml")

In [4]:
UEA_MTSC30 = ['EthanolConcentration',
              'FaceDetection',
              'Handwriting',
              'Heartbeat',
              'JapaneseVowels',
              'PEMS-SF',
              'SelfRegulationSCP1',
              'SelfRegulationSCP2',
              'SpokenArabicDigits',
              'UWaveGestureLibrary',
              'ArticularyWordRecognition',
              'AtrialFibrillation',
              'BasicMotions',
              'CharacterTrajectories',
              'Cricket',
              'DuckDuckGeese',
              'EigenWorms',
              'Epilepsy',
              'ERing',
              'FingerMovements',
              'HandMovementDirection',
              'InsectWingbeat',
              'Libras',
              'LSST',
              'MotorImagery',
              'NATOPS',
              'PenDigits',
              'PhonemeSpectra',
              'RacketSports',
              'StandWalkJump']

In [5]:
from omegaconf import OmegaConf
data_info = OmegaConf.load(f"../data_classification.yaml")

In [6]:
model = 'MambaSL'
result_dict = dict()

for data_name in UEA_MTSC30:
    try:
        with open(f'../03-full_results/{model}/_proposed/{model}_CLS_{data_name}_proposed.out', 'r') as file:
            data = file.read().splitlines()
    except:
        continue
    
    result_lst = list()
    for i in range(len(data)):
        if data[i].startswith('>>>>>>>testing : '):
            data_meta = list(data[i][17:-33].split('_'))
            data_meta[6] = int(data_meta[6].replace('sl', ''))
            data_meta[7] = int(data_meta[7].replace('ll', ''))
            data_meta[8] = int(data_meta[8].replace('pl', ''))
            data_meta[9] = int(data_meta[9].replace('dm', ''))
            data_meta[10] = int(data_meta[10].replace('ds', ''))
            data_meta[11] = int(data_meta[11].replace('expand', ''))
            data_meta[12] = int(data_meta[12].replace('dc', ''))
            data_meta[13] = int(data_meta[13].replace('nk', ''))
            data_meta[14] = bool(int(data_meta[14].replace('tvdt', '')))
            data_meta[15] = bool(int(data_meta[15].replace('tvB', '')))
            data_meta[16] = bool(int(data_meta[16].replace('tvC', '')))
            data_meta[17] = bool(int(data_meta[17].replace('useD', '')))
            if data[i+2].startswith('gating_value'):
                acc = float(data[i+3].replace('accuracy:', ''))
                model_params = data[i+4].replace('model parameter : ', '')
                model_size = data[i+5].replace('model size : ', '').replace('MB', '')
            else:
                acc = float(data[i+2].replace('accuracy:', ''))
                model_params = data[i+3].replace('model parameter : ', '')
                model_size = data[i+4].replace('model size : ', '').replace('MB', '')


            result_data = {
                # 'task': data_meta[0],
                # 'model_id': data_meta[1],
                'data_name': data_meta[2],
                'model': data_meta[3],
                # 'data': data_meta[4],
                # 'feature': data_meta[5],
                'seq_len': data_meta[6],
                # 'label_len': data_meta[7],
                # 'pred_len': data_meta[8],
                'e_layers': 1,
                'd_model': data_meta[9],
                'd_state': data_meta[10],
                'expand': data_meta[11],
                'd_conv': data_meta[12],
                'num_kernel': data_meta[13],
                'tv_dt': data_meta[14],
                'tv_B': data_meta[15],
                'tv_C': data_meta[16],
                'use_D': data_meta[17],
                'exp': data_meta[18],
                # 'desc': data_meta[19],
                'acc': acc,
                'model_params': int(model_params),
                'model_size (MB)': float(model_size),
                'ckpt': data[i].replace('>>>>>>>testing : ', '').replace('<', ''),
            }

            result_lst.append(result_data)

    try:
        # with open(f'../03-full_results/{model}/multilayer/{model}_CLS_{data_name}_multilayer.out', 'r') as file:
        with open(f'../results/fin/multilayer/MambaML_CLS_{data_name}_multilayer.out', 'r') as file:
            data = file.read().splitlines()
    except:
        continue
    
    # result_lst = list()
    for i in range(len(data)):
        if data[i].startswith('>>>>>>>testing : '):
            data_meta = list(data[i][17:-33].split('_'))
            data_meta[6] = int(data_meta[6].replace('sl', ''))
            data_meta[7] = int(data_meta[7].replace('ll', ''))
            data_meta[8] = int(data_meta[8].replace('pl', ''))
            data_meta[9] = int(data_meta[9].replace('el', ''))
            data_meta[10] = int(data_meta[10].replace('dm', ''))
            data_meta[11] = int(data_meta[11].replace('ds', ''))
            data_meta[12] = int(data_meta[12].replace('expand', ''))
            data_meta[13] = int(data_meta[13].replace('dc', ''))
            data_meta[14] = int(data_meta[14].replace('nk', ''))
            data_meta[15] = bool(int(data_meta[15].replace('tvdt', '')))
            data_meta[16] = bool(int(data_meta[16].replace('tvB', '')))
            data_meta[17] = bool(int(data_meta[17].replace('tvC', '')))
            data_meta[18] = bool(int(data_meta[18].replace('useD', '')))
            if data[i+2].startswith('gating_value'):
                acc = float(data[i+3].replace('accuracy:', ''))
                model_params = data[i+4].replace('model parameter : ', '')
                model_size = data[i+5].replace('model size : ', '').replace('MB', '')
            else:
                acc = float(data[i+2].replace('accuracy:', ''))
                model_params = data[i+3].replace('model parameter : ', '')
                model_size = data[i+4].replace('model size : ', '').replace('MB', '')


            result_data = {
                # 'task': data_meta[0],
                # 'model_id': data_meta[1],
                'data_name': data_meta[2],
                'model': data_meta[3],
                # 'data': data_meta[4],
                # 'feature': data_meta[5],
                'seq_len': data_meta[6],
                # 'label_len': data_meta[7],
                # 'pred_len': data_meta[8],
                'e_layers': data_meta[9],
                'd_model': data_meta[10],
                'd_state': data_meta[11],
                'expand': data_meta[12],
                'd_conv': data_meta[13],
                'num_kernel': data_meta[14],
                'tv_dt': data_meta[15],
                'tv_B': data_meta[16],
                'tv_C': data_meta[17],
                'use_D': data_meta[18],
                'exp': data_meta[19],
                # 'desc': data_meta[20],
                'acc': acc,
                'model_params': int(model_params),
                'model_size (MB)': float(model_size),
                'ckpt': data[i].replace('>>>>>>>testing : ', '').replace('<', '')
            }

            result_lst.append(result_data)

    result_df = pd.DataFrame(result_lst)
    # os.makedirs(f'./{model}', exist_ok=True)
    # result_df.to_csv(f'./{model}/{data_name}.csv', index=False)
    result_dict[data_name] = result_df.copy()

    print(data_name, len(result_df))
    print(f'best result: {result_df.loc[result_df["e_layers"] == 1]["acc"].max():.3f} (1 layer)')
    print(f'best result: {result_df.loc[result_df["e_layers"] == 2]["acc"].max():.3f} (2 layers)')
    print(f'best result: {result_df.loc[result_df["e_layers"] == 3]["acc"].max():.3f} (3 layers)')

    # cols = ['e_layers', 'd_model', 'd_state', 'tv_dt', 'tv_B', 'tv_C']
    # num_cols, num_rows = 3, 2

    # # Lineplot
    # sns.set_theme(style="whitegrid")
    # sns.set_context("paper", font_scale=1)
    # fig, axs = plt.subplots(ncols=num_cols, nrows=num_rows, figsize=(8, 3.5), sharey=False)
    # for i, col in enumerate(cols):
    #     if col == 'e_layers':
    #         sns.boxplot(x=col, y='acc', data=result_df, ax=axs[i//num_cols][i%num_cols], legend=False, 
    #                     hue='e_layers', palette='Set2')
    #     else:
    #         sns.lineplot(x=col, y='acc', data=result_df, ax=axs[i//num_cols][i%num_cols], legend=False, 
    #                      style='e_layers', markers=True, hue='e_layers', palette='Set2')
    #         # sns.lineplot(x=col, y='acc', data=result_df.groupby([col, 'e_layers']).max(), 
    #         #              ax=axs[i//num_cols][i%num_cols], legend=False, 
    #         #              style='e_layers', markers=True, hue='e_layers', palette='pastel')
    # for i in range(len(cols), num_cols*num_rows):
    #     fig.delaxes(axs[i//num_cols][i%num_cols])
    # fig.suptitle(f'{data_name} - {model}', fontsize=10)
    # plt.tight_layout()
    # plt.subplots_adjust(top=0.85)
    # display(fig)
    # # plt.savefig(f'./{model}/{data_name}.png', dpi=300, bbox_inches='tight')
    # plt.close(fig)

EthanolConcentration 720
best result: 0.426 (1 layer)
best result: 0.411 (2 layers)
best result: 0.418 (3 layers)
FaceDetection 720
best result: 0.693 (1 layer)
best result: 0.688 (2 layers)
best result: 0.691 (3 layers)
Handwriting 720
best result: 0.608 (1 layer)
best result: 0.658 (2 layers)
best result: 0.664 (3 layers)
Heartbeat 720
best result: 0.805 (1 layer)
best result: 0.805 (2 layers)
best result: 0.805 (3 layers)
JapaneseVowels 720
best result: 0.986 (1 layer)
best result: 0.986 (2 layers)
best result: 0.984 (3 layers)
PEMS-SF 720
best result: 0.855 (1 layer)
best result: 0.855 (2 layers)
best result: 0.867 (3 layers)
SelfRegulationSCP1 720
best result: 0.925 (1 layer)
best result: 0.922 (2 layers)
best result: 0.911 (3 layers)
SelfRegulationSCP2 720
best result: 0.650 (1 layer)
best result: 0.628 (2 layers)
best result: 0.622 (3 layers)
SpokenArabicDigits 720
best result: 1.000 (1 layer)
best result: 0.999 (2 layers)
best result: 0.999 (3 layers)
UWaveGestureLibrary 720
best result: 0.934 (1 layer)
best result: 0.934 (2 layers)
best result: 0.931 (3 layers)
ArticularyWordRecognition 720
best result: 0.993 (1 layer)
best result: 0.993 (2 layers)
best result: 0.993 (3 layers)
AtrialFibrillation 720
best result: 0.533 (1 layer)
best result: 0.533 (2 layers)
best result: 0.600 (3 layers)
BasicMotions 720
best result: 1.000 (1 layer)
best result: 1.000 (2 layers)
best result: 1.000 (3 layers)
CharacterTrajectories 720
best result: 0.997 (1 layer)
best result: 0.997 (2 layers)
best result: 0.997 (3 layers)
Cricket 720
best result: 1.000 (1 layer)
best result: 1.000 (2 layers)
best result: 1.000 (3 layers)
DuckDuckGeese 720
best result: 0.700 (1 layer)
best result: 0.700 (2 layers)
best result: 0.680 (3 layers)
EigenWorms 720
best result: 0.840 (1 layer)
best result: 0.832 (2 layers)
best result: 0.855 (3 layers)
Epilepsy 720
best result: 0.978 (1 layer)
best result: 0.978 (2 layers)
best result: 0.971 (3 layers)
ERing 720
best result: 0.937 (1 layer)
best result: 0.952 (2 layers)
best result: 0.941 (3 layers)
FingerMovements 720
best result: 0.710 (1 layer)
best result: 0.670 (2 layers)
best result: 0.650 (3 layers)
HandMovementDirection 720
best result: 0.703 (1 layer)
best result: 0.689 (2 layers)
best result: 0.689 (3 layers)
InsectWingbeat 720
best result: 0.663 (1 layer)
best result: 0.661 (2 layers)
best result: 0.656 (3 layers)
Libras 720
best result: 0.917 (1 layer)
best result: 0.911 (2 layers)
best result: 0.894 (3 layers)
LSST 720
best result: 0.456 (1 layer)
best result: 0.440 (2 layers)
best result: 0.425 (3 layers)
MotorImagery 720
best result: 0.690 (1 layer)
best result: 0.670 (2 layers)
best result: 0.660 (3 layers)
NATOPS 720
best result: 0.989 (1 layer)
best result: 0.989 (2 layers)
best result: 0.983 (3 layers)
PenDigits 720
best result: 0.993 (1 layer)
best result: 0.992 (2 layers)
best result: 0.992 (3 layers)
PhonemeSpectra 684
best result: 0.303 (1 layer)
best result: 0.314 (2 layers)
best result: 0.310 (3 layers)
RacketSports 720
best result: 0.928 (1 layer)
best result: 0.934 (2 layers)
best result: 0.928 (3 layers)
StandWalkJump 720
best result: 0.733 (1 layer)
best result: 0.667 (2 layers)
best result: 0.667 (3 layers)

In [7]:
model_configs = {
    "e_layers" : [1, 2, 3],
    "d_model" : [32, 64, 128, 256, 512, 1024],
    "d_ff" : [1, 2, 4, 8, 16],
    "tv_dt" : [False, True],
    "tv_B" : [False, True],
    "tv_C" : [False, True],
}

hyperparameter_combinations = make_combination(model_configs)

acc_all_df = pd.DataFrame(index=UEA_MTSC30, 
                          columns=[str(hp_comb) for hp_comb in hyperparameter_combinations])
for data_name in UEA_MTSC30:
    acc_data_dict = dict()
    for hyperparameter_combination in hyperparameter_combinations:
        seq_len = data_info[f'CLS_{data_name}']["seq_len"]
        e_layers = hyperparameter_combination['e_layers']
        d_model = hyperparameter_combination['d_model']
        d_ff = hyperparameter_combination['d_ff']
        tv_dt = hyperparameter_combination['tv_dt']
        tv_B = hyperparameter_combination['tv_B']
        tv_C = hyperparameter_combination['tv_C']

        if result_dict.get(data_name) is None:
            continue

        tmp = result_dict[data_name]
        try:
            acc = tmp[
                (tmp['d_model'] == d_model)
                & (tmp['e_layers'] == e_layers)
                & (tmp['d_state'] == d_ff)
                & (tmp['tv_dt'] == tv_dt)
                & (tmp['tv_B'] == tv_B)
                & (tmp['tv_C'] == tv_C)
            ]['acc'].values[0]
        except:
            acc = None
            print(f'no acc for {data_name} with {hyperparameter_combination}')
        acc_data_dict[str(hyperparameter_combination)] = acc

    acc_all_df.loc[data_name] = pd.Series(acc_data_dict)

no acc for PhonemeSpectra with {'e_layers': 2, 'd_model': 32, 'd_ff': 1, 'tv_dt': False, 'tv_B': False, 'tv_C': False}
no acc for PhonemeSpectra with {'e_layers': 2, 'd_model': 32, 'd_ff': 1, 'tv_dt': False, 'tv_B': False, 'tv_C': True}
no acc for PhonemeSpectra with {'e_layers': 2, 'd_model': 32, 'd_ff': 1, 'tv_dt': False, 'tv_B': True, 'tv_C': False}
no acc for PhonemeSpectra with {'e_layers': 2, 'd_model': 32, 'd_ff': 1, 'tv_dt': False, 'tv_B': True, 'tv_C': True}
no acc for PhonemeSpectra with {'e_layers': 2, 'd_model': 32, 'd_ff': 1, 'tv_dt': True, 'tv_B': False, 'tv_C': False}
no acc for PhonemeSpectra with {'e_layers': 2, 'd_model': 32, 'd_ff': 1, 'tv_dt': True, 'tv_B': False, 'tv_C': True}
no acc for PhonemeSpectra with {'e_layers': 2, 'd_model': 32, 'd_ff': 1, 'tv_dt': True, 'tv_B': True, 'tv_C': False}
no acc for PhonemeSpectra with {'e_layers': 2, 'd_model': 32, 'd_ff': 1, 'tv_dt': True, 'tv_B': True, 'tv_C': True}
no acc for PhonemeSpectra with {'e_layers': 2, 'd_model': 32, 'd_ff': 2, 'tv_dt': False, 'tv_B': False, 'tv_C': False}
no acc for PhonemeSpectra with {'e_layers': 2, 'd_model': 32, 'd_ff': 2, 'tv_dt': False, 'tv_B': False, 'tv_C': True}
no acc for PhonemeSpectra with {'e_layers': 2, 'd_model': 32, 'd_ff': 2, 'tv_dt': False, 'tv_B': True, 'tv_C': False}
no acc for PhonemeSpectra with {'e_layers': 2, 'd_model': 32, 'd_ff': 2, 'tv_dt': False, 'tv_B': True, 'tv_C': True}
no acc for PhonemeSpectra with {'e_layers': 2, 'd_model': 32, 'd_ff': 2, 'tv_dt': True, 'tv_B': False, 'tv_C': False}
no acc for PhonemeSpectra with {'e_layers': 2, 'd_model': 32, 'd_ff': 2, 'tv_dt': True, 'tv_B': False, 'tv_C': True}
no acc for PhonemeSpectra with {'e_layers': 2, 'd_model': 32, 'd_ff': 2, 'tv_dt': True, 'tv_B': True, 'tv_C': False}
no acc for PhonemeSpectra with {'e_layers': 2, 'd_model': 32, 'd_ff': 2, 'tv_dt': True, 'tv_B': True, 'tv_C': True}
no acc for PhonemeSpectra with {'e_layers': 2, 'd_model': 32, 'd_ff': 4, 'tv_dt': False, 'tv_B': False, 'tv_C': False}
no acc for PhonemeSpectra with {'e_layers': 2, 'd_model': 32, 'd_ff': 4, 'tv_dt': False, 'tv_B': False, 'tv_C': True}
no acc for PhonemeSpectra with {'e_layers': 2, 'd_model': 32, 'd_ff': 4, 'tv_dt': False, 'tv_B': True, 'tv_C': False}
no acc for PhonemeSpectra with {'e_layers': 2, 'd_model': 32, 'd_ff': 4, 'tv_dt': False, 'tv_B': True, 'tv_C': True}
no acc for PhonemeSpectra with {'e_layers': 2, 'd_model': 32, 'd_ff': 4, 'tv_dt': True, 'tv_B': False, 'tv_C': False}
no acc for PhonemeSpectra with {'e_layers': 2, 'd_model': 32, 'd_ff': 4, 'tv_dt': True, 'tv_B': False, 'tv_C': True}
no acc for PhonemeSpectra with {'e_layers': 2, 'd_model': 32, 'd_ff': 4, 'tv_dt': True, 'tv_B': True, 'tv_C': False}
no acc for PhonemeSpectra with {'e_layers': 2, 'd_model': 32, 'd_ff': 4, 'tv_dt': True, 'tv_B': True, 'tv_C': True}
no acc for PhonemeSpectra with {'e_layers': 2, 'd_model': 32, 'd_ff': 8, 'tv_dt': False, 'tv_B': False, 'tv_C': False}
no acc for PhonemeSpectra with {'e_layers': 2, 'd_model': 32, 'd_ff': 8, 'tv_dt': False, 'tv_B': False, 'tv_C': True}
no acc for PhonemeSpectra with {'e_layers': 2, 'd_model': 32, 'd_ff': 8, 'tv_dt': False, 'tv_B': True, 'tv_C': False}
no acc for PhonemeSpectra with {'e_layers': 2, 'd_model': 32, 'd_ff': 8, 'tv_dt': False, 'tv_B': True, 'tv_C': True}
no acc for PhonemeSpectra with {'e_layers': 2, 'd_model': 32, 'd_ff': 8, 'tv_dt': True, 'tv_B': False, 'tv_C': False}
no acc for PhonemeSpectra with {'e_layers': 2, 'd_model': 32, 'd_ff': 8, 'tv_dt': True, 'tv_B': False, 'tv_C': True}
no acc for PhonemeSpectra with {'e_layers': 2, 'd_model': 32, 'd_ff': 8, 'tv_dt': True, 'tv_B': True, 'tv_C': False}
no acc for PhonemeSpectra with {'e_layers': 2, 'd_model': 32, 'd_ff': 8, 'tv_dt': True, 'tv_B': True, 'tv_C': True}
no acc for PhonemeSpectra with {'e_layers': 2, 'd_model': 32, 'd_ff': 16, 'tv_dt': False, 'tv_B': False, 'tv_C': False}
no acc for PhonemeSpectra with {'e_layers': 2, 'd_model': 32, 'd_ff': 16, 'tv_dt': False, 'tv_B': False, 'tv_C': True}
no acc for PhonemeSpectra with {'e_layers': 2, 'd_model': 32, 'd_ff': 16, 'tv_dt': False, 'tv_B': True, 'tv_C': False}
no acc for PhonemeSpectra with {'e_layers': 2, 'd_model': 32, 'd_ff': 16, 'tv_dt': False, 'tv_B': True, 'tv_C': True}

In [8]:
acc_all_df.loc[:,'max_1'] = acc_all_df.loc[:,[col for col in acc_all_df.columns if "'e_layers': 1" in col]].max(axis=1)
acc_all_df.loc[:,'max_2'] = acc_all_df.loc[:,[col for col in acc_all_df.columns if "'e_layers': 2" in col]].max(axis=1)
acc_all_df.loc[:,'max_3'] = acc_all_df.loc[:,[col for col in acc_all_df.columns if "'e_layers': 3" in col]].max(axis=1)
acc_all_df.loc[:,'max'] = acc_all_df.max(axis=1)
acc_all_df.loc['avg'] = acc_all_df.mean(axis=0)
acc_all_df.sort_values(by='avg', ascending=False, inplace=True, axis=1)
acc_all_df

,max,max_1,max_2,max_3,"{'e_layers': 1, 'd_model': 1024, 'd_ff': 8, 'tv_dt': False, 'tv_B': False, 'tv_C': False}","{'e_layers': 2, 'd_model': 512, 'd_ff': 16, 'tv_dt': False, 'tv_B': False, 'tv_C': False}","{'e_layers': 2, 'd_model': 512, 'd_ff': 16, 'tv_dt': False, 'tv_B': False, 'tv_C': True}","{'e_layers': 1, 'd_model': 1024, 'd_ff': 16, 'tv_dt': False, 'tv_B': False, 'tv_C': True}","{'e_layers': 1, 'd_model': 1024, 'd_ff': 8, 'tv_dt': False, 'tv_B': False, 'tv_C': True}","{'e_layers': 1, 'd_model': 1024, 'd_ff': 4, 'tv_dt': False, 'tv_B': False, 'tv_C': False}",...,"{'e_layers': 1, 'd_model': 32, 'd_ff': 4, 'tv_dt': True, 'tv_B': False, 'tv_C': False}","{'e_layers': 3, 'd_model': 32, 'd_ff': 4, 'tv_dt': False, 'tv_B': False, 'tv_C': True}","{'e_layers': 3, 'd_model': 32, 'd_ff': 1, 'tv_dt': True, 'tv_B': True, 'tv_C': True}","{'e_layers': 3, 'd_model': 32, 'd_ff': 1, 'tv_dt': True, 'tv_B': True, 'tv_C': False}","{'e_layers': 3, 'd_model': 32, 'd_ff': 1, 'tv_dt': False, 'tv_B': False, 'tv_C': True}","{'e_layers': 3, 'd_model': 32, 'd_ff': 1, 'tv_dt': True, 'tv_B': False, 'tv_C': True}","{'e_layers': 3, 'd_model': 32, 'd_ff': 8, 'tv_dt': False, 'tv_B': True, 'tv_C': True}","{'e_layers': 3, 'd_model': 32, 'd_ff': 2, 'tv_dt': False, 'tv_B': False, 'tv_C': True}","{'e_layers': 3, 'd_model': 32, 'd_ff': 16, 'tv_dt': True, 'tv_B': True, 'tv_C': True}","{'e_layers': 3, 'd_model': 32, 'd_ff': 1, 'tv_dt': False, 'tv_B': True, 'tv_C': True}"
EthanolConcentration,0.425856,0.425856,0.410646,0.418251,0.403042,0.372624,0.391635,0.395437,0.395437,0.387833,...,0.296578,0.315589,0.292776,0.292776,0.292776,0.281369,0.26616,0.296578,0.30038,0.30038
FaceDetection,0.692963,0.692963,0.687855,0.690976,0.670261,0.680193,0.683882,0.678207,0.681044,0.662316,...,0.637911,0.63479,0.63706,0.644722,0.631669,0.638479,0.643587,0.63025,0.632804,0.569523
Handwriting,0.663529,0.608235,0.657647,0.663529,0.588235,0.642353,0.623529,0.587059,0.588235,0.592941,...,0.044706,0.405882,0.410588,0.290588,0.057647,0.047059,0.405882,0.045882,0.037647,0.38
Heartbeat,0.804878,0.804878,0.804878,0.804878,0.780488,0.785366,0.770732,0.77561,0.765854,0.770732,...,0.770732,0.780488,0.77561,0.765854,0.765854,0.770732,0.77561,0.795122,0.765854,0.780488
JapaneseVowels,0.986486,0.986486,0.986486,0.983784,0.978378,0.967568,0.967568,0.978378,0.962162,0.975676,...,0.964865,0.945946,0.967568,0.954054,0.962162,0.940541,0.956757,0.951351,0.967568,0.964865
PEMS-SF,0.867052,0.855491,0.855491,0.867052,0.809249,0.83237,0.803468,0.797688,0.786127,0.815029,...,0.768786,0.751445,0.757225,0.797688,0.722543,0.82659,0.716763,0.734104,0.705202,0.757225
SelfRegulationSCP1,0.924915,0.924915,0.921502,0.911263,0.87372,0.877133,0.890785,0.901024,0.856655,0.877133,...,0.887372,0.860068,0.849829,0.856655,0.883959,0.860068,0.846416,0.877133,0.849829,0.767918
SelfRegulationSCP2,0.65,0.65,0.627778,0.622222,0.577778,0.588889,0.577778,0.566667,0.538889,0.561111,...,0.572222,0.544444,0.511111,0.527778,0.511111,0.583333,0.5,0.533333,0.522222,0.511111
SpokenArabicDigits,0.999545,0.999545,0.998636,0.998636,0.994543,0.995452,0.993179,0.989541,0.995452,0.994543,...,0.984538,0.979081,0.986812,0.9809,0.982265,0.979081,0.985903,0.984538,0.991814,0.983174
UWaveGestureLibrary,0.934375,0.934375,0.934375,0.93125,0.93125,0.928125,0.9125,0.91875,0.925,0.925,...,0.896875,0.85,0.896875,0.8375,0.865625,0.85,0.2,0.89375,0.84375,0.221875
ArticularyWordRecognition,0.993333,0.993333,0.993333,0.993333,0.986667,0.986667,0.983333,0.99,0.986667,0.986667,...,0.956667,0.976667,0.956667,0.96,0.953333,0.95,0.976667,0.956667,0.98,0.946667
AtrialFibrillation,0.6,0.533333,0.533333,0.6,0.4,0.4,0.333333,0.466667,0.4,0.4,...,0.466667,0.266667,0.333333,0.4,0.333333,0.2,0.333333,0.466667,0.466667,0.466667
BasicMotions,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.95,0.275,0.5,0.325,0.65,0.275,0.325,0.4,0.425,0.4
CharacterTrajectories,0.997214,0.997214,0.996518,0.997214,0.991643,0.986769,0.990251,0.990251,0.993036,0.993733,...,0.991643,0.991643,0.990251,0.99234,0.991643,0.994429,0.99234,0.99234,0.99234,0.990947
Cricket,1.0,1.0,1.0,1.0,0.986111,0.986111,0.986111,0.986111,0.986111,0.986111,...,0.958333,0.986111,0.972222,0.986111,0.958333,0.958333,0.986111,0.972222,0.138889,0.097222
DuckDuckGeese,0.7,0.7,0.7,0.68,0.68,0.6,0.66,0.6,0.58,0.64,...,0.58,0.52,0.26,0.3,0.54,0.36,0.3,0.3,0.28,0.32
EigenWorms,0.854962,0.839695,0.832061,0.854962,0.717557,0.801527,0.763359,0.801527,0.78626,0.748092,...,0.793893,0.748092,0.763359,0.633588,0.679389,0.694656,0.679389,0.770992,0.709924,0.816794
Epilepsy,0.978261,0.978261,0.978261,0.971014,0.956522,0.949275,0.963768,0.956522,0.963768,0.956522,...,0.949275,0.934783,0.905797,0.934783,0.934783,0.905797,0.92029,0.934783,0.942029,0.92029
ERing,0.951852,0.937037,0.951852,0.940741,0.922222,0.914815,0.92963,0.918519,0.914815,0.925926,...,0.174074,0.366667,0.214815,0.366667,0.362963,0.207407,0.411111,0.292593,0.303704,0.348148
FingerMovements,0.71,0.71,0.67,0.65,0.63,0.57,0.63,0.59,0.59,0.59,...,0.58,0.52,0.52,0.56,0.56,0.55,0.53,0.57,0.58,0.57
HandMovementDirection,0.702703,0.702703,0.689189,0.689189,0.635135,0.581081,0.621622,0.581081,0.594595,0.608108,...,0.405405,0.22973,0.459459,0.405405,0.364865,0.418919,0.405405,0.243243,0.243243,0.445946
InsectWingbeat,0.66304,0.66304,0.66104,0.65596,0.66304,0.65552,0.65348,0.65572,0.66016,0.66292,...,0.64196,0.64496,0.5938,0.63908,0.63692,0.6244,0.61236,0.63552,0.64552,0.63276
Libras,0.916667,0.916667,0.911111,0.894444,0.866667,0.877778,0.855556,0.838889,0.855556,0.883333,...,0.183333,0.8,0.783333,0.766667,0.111111,0.75,0.788889,0.788889,0.85,0.788889
LSST,0.455799,0.455799,0.440389,0.425385,0.415653,0.408354,0.388078,0.404704,0.407948,0.424169,...,0.398621,0.373479,0.376318,0.373885,0.360503,0.371857,0.351582,0.375507,0.363747,0.358475
MotorImagery,0.69,0.69,0.67,0.66,0.61,0.58,0.59,0.57,0.61,0.61,...,0.5,0.56,0.51,0.56,0.54,0.58,0.5,0.6,0.53,0.54
NATOPS,0.988889,0.988889,0.988889,0.983333,0.955556,0.955556,0.955556,0.977778,0.961111,0.955556,...,0.85,0.922222,0.872222,0.911111,0.922222,0.933333,0.855556,0.938889,0.938889,0.844444
PenDigits,0.992567,0.992567,0.99171,0.991995,0.984277,0.988851,0.988279,0.987136,0.983133,0.984563,...,0.98542,0.987136,0.988851,0.985706,0.985706,0.983991,0.987421,0.977987,0.991995,0.98542
PhonemeSpectra,0.314345,0.30331,0.314345,0.309872,0.273486,0.299433,0.304205,0.289293,0.278557,0.261855,...,0.269013,0.271995,0.270206,0.265136,0.249627,0.270206,0.261259,0.265732,0.290486,0.276171
RacketSports,0.934211,0.927632,0.934211,0.927632,0.907895,0.894737,0.921053,0.901316,0.894737,0.894737,...,0.75,0.868421,0.842105,0.809211,0.855263,0.822368,0.855263,0.328947,0.855263,0.842105
StandWalkJump,0.733333,0.733333,0.666667,0.666667,0.466667,0.533333,0.466667,0.466667,0.6,0.466667,...,0.466667,0.333333,0.4,0.333333,0.466667,0.333333,0.533333,0.333333,0.466667,0.466667
avg,0.804226,0.798185,0.793607,0.792786,0.755201,0.754663,0.753311,0.752018,0.751377,0.751376,...,0.655852,0.654821,0.653273,0.648551,0.637742,0.632043,0.63008,0.629545,0.620381,0.609806

In [9]:
pd.set_option("display.precision", 14)
acc_all_df.loc[:,['max_1', 'max_2', 'max_3', 'max']]

,max_1,max_2,max_3,max
EthanolConcentration,0.42585551330798,0.4106463878327,0.41825095057034,0.42585551330798
FaceDetection,0.69296254256527,0.68785471055619,0.69097616345062,0.69296254256527
Handwriting,0.60823529411765,0.65764705882353,0.66352941176471,0.66352941176471
Heartbeat,0.80487804878049,0.80487804878049,0.80487804878049,0.80487804878049
JapaneseVowels,0.98648648648649,0.98648648648649,0.98378378378378,0.98648648648649
PEMS-SF,0.85549132947977,0.85549132947977,0.86705202312139,0.86705202312139
SelfRegulationSCP1,0.92491467576792,0.92150170648464,0.91126279863481,0.92491467576792
SelfRegulationSCP2,0.65,0.62777777777778,0.62222222222222,0.65
SpokenArabicDigits,0.99954524783993,0.99863574351978,0.99863574351978,0.99954524783993
UWaveGestureLibrary,0.934375,0.934375,0.93125,0.934375
ArticularyWordRecognition,0.99333333333333,0.99333333333333,0.99333333333333,0.99333333333333
AtrialFibrillation,0.53333333333333,0.53333333333333,0.6,0.6
BasicMotions,1.0,1.0,1.0,1.0
CharacterTrajectories,0.99721448467967,0.99651810584958,0.99721448467967,0.99721448467967
Cricket,1.0,1.0,1.0,1.0
DuckDuckGeese,0.7,0.7,0.68,0.7
EigenWorms,0.83969465648855,0.83206106870229,0.85496183206107,0.85496183206107
Epilepsy,0.97826086956522,0.97826086956522,0.97101449275362,0.97826086956522
ERing,0.93703703703704,0.95185185185185,0.94074074074074,0.95185185185185
FingerMovements,0.71,0.67,0.65,0.71
HandMovementDirection,0.7027027027027,0.68918918918919,0.68918918918919,0.7027027027027
InsectWingbeat,0.66304,0.66104,0.65596,0.66304
Libras,0.91666666666667,0.91111111111111,0.89444444444444,0.91666666666667
LSST,0.45579886455799,0.44038929440389,0.42538523925385,0.45579886455799
MotorImagery,0.69,0.67,0.66,0.69
NATOPS,0.98888888888889,0.98888888888889,0.98333333333333,0.98888888888889
PenDigits,0.99256718124643,0.99170954831332,0.99199542595769,0.99256718124643
PhonemeSpectra,0.3033104682374,0.31434536236206,0.30987175663585,0.31434536236206
RacketSports,0.92763157894737,0.93421052631579,0.92763157894737,0.93421052631579
StandWalkJump,0.73333333333333,0.66666666666667,0.66666666666667,0.73333333333333
avg,0.79818525124545,0.7936067799876,0.79278612212817,0.80422582823997

In [10]:
ranked_df = acc_all_df.loc[[idx for idx in acc_all_df.index if 'avg' not in idx],
                           ['max_1', 'max_2', 'max_3']].rank(ascending=False, method='min', axis=1)
print(f'AVG RANK: \n{ranked_df.mean(axis=0)}')
ranked_df

AVG RANK:
max_1    1.33333333333333
max_2    1.76666666666667
max_3    2.10000000000000
dtype: float64

                           max_1  max_2  max_3
EthanolConcentration         1.0    3.0    2.0
FaceDetection                1.0    3.0    2.0
Handwriting                  3.0    2.0    1.0
Heartbeat                    1.0    1.0    1.0
JapaneseVowels               1.0    1.0    3.0
PEMS-SF                      2.0    2.0    1.0
SelfRegulationSCP1           1.0    2.0    3.0
SelfRegulationSCP2           1.0    2.0    3.0
SpokenArabicDigits           1.0    2.0    2.0
UWaveGestureLibrary          1.0    1.0    3.0
ArticularyWordRecognition    1.0    1.0    1.0
AtrialFibrillation           2.0    2.0    1.0
BasicMotions                 1.0    1.0    1.0
CharacterTrajectories        1.0    3.0    1.0
Cricket                      1.0    1.0    1.0
DuckDuckGeese                1.0    1.0    3.0
EigenWorms                   2.0    3.0    1.0
Epilepsy                     1.0    1.0    3.0
ERing                        3.0    1.0    2.0
FingerMovements              1.0    2.0    3.0
HandMovementDirection        1.0    2.0    2.0
InsectWingbeat               1.0    2.0    3.0
Libras                       1.0    2.0    3.0
LSST                         1.0    2.0    3.0
MotorImagery                 1.0    2.0    3.0
NATOPS                       1.0    1.0    3.0
PenDigits                    1.0    3.0    2.0
PhonemeSpectra               3.0    1.0    2.0
RacketSports                 2.0    1.0    2.0
StandWalkJump                1.0    2.0    2.0