In [1]:
import os
import torch, gc
gc.collect()
torch.cuda.empty_cache()

In [2]:
import pandas as pd

In [3]:
UEA_MTSC30 = ['EthanolConcentration',
              'FaceDetection',
              'Handwriting',
              'Heartbeat',
              'JapaneseVowels',
              'PEMS-SF',
              'SelfRegulationSCP1',
              'SelfRegulationSCP2',
              'SpokenArabicDigits',
              'UWaveGestureLibrary',
              'ArticularyWordRecognition',
              'AtrialFibrillation',
              'BasicMotions',
              'CharacterTrajectories',
              'Cricket',
              'DuckDuckGeese',
              'EigenWorms',
              'Epilepsy',
              'ERing',
              'FingerMovements',
              'HandMovementDirection',
              'InsectWingbeat',
              'Libras',
              'LSST',
              'MotorImagery',
              'NATOPS',
              'PenDigits',
              'PhonemeSpectra',
              'RacketSports',
              'StandWalkJump']

In [4]:
ckpt_dir = '/data/yoom618/TSLib/checkpoints/'
best_ckpt_dir = '/data/yoom618/TSLib/checkpoints_final/'
best_script_dir = '/data/yoom618/TSLib/scripts_final/'
full_results_dir = '/home/yoom618/TSLib/scripts_classification/03-full_results/MambaSL/additional (multilayer)'
model = 'MambaML'

for n_layers in [2,3]:
    print(f'==================={model}===================')
    os.makedirs(os.path.join(best_ckpt_dir, model), exist_ok=True)

    for data_name in UEA_MTSC30:

        if os.path.exists(f'{full_results_dir}/{model}_CLS_{data_name}_multilayer.out'):
            with open(f'{full_results_dir}/{model}_CLS_{data_name}_multilayer.out', 'r') as file:
                data = file.read().splitlines()
            with open(f'{full_results_dir}/{model}_CLS_{data_name}_multilayer.sh', 'r') as file:
                scripts = file.read().split('\n\n')[:-1]
                scripts = list(filter(lambda x: x[0] != '#', scripts))
        else:
            # print('no file')
            continue


        print(data_name)
        result_lst = list()
        for i in range(len(data)):
            if data[i].startswith('>>>>>>>testing : '):
                ckpt = data[i].replace('>>>>>>>testing : ', '').replace('<', '').strip()
                data_meta = ckpt.split('_')

                if data[i+2].startswith('gating_value'):
                    acc = float(data[i+3].replace('accuracy:', ''))
                    model_params = data[i+4].replace('model parameter : ', '')
                    model_size = data[i+5].replace('model size : ', '').replace('MB', '')
                else:
                    acc = float(data[i+2].replace('accuracy:', ''))
                    model_params = data[i+3].replace('model parameter : ', '')
                    model_size = data[i+4].replace('model size : ', '').replace('MB', '')

                result_data = {
                    i: data_meta[i] for i in range(9, len(data_meta))
                }
                result_data.update({
                    'acc': float(acc),
                    'model_params': int(model_params),
                    'model_size (MB)': float(model_size),
                    'ckpt': ckpt,
                    'n_layers': int(ckpt.split('_el')[1].split('_')[0])
                })

                result_lst.append(result_data)

        result_df = pd.DataFrame(reversed(result_lst))
        scripts = list(reversed(scripts))
        
        acc_max = result_df.loc[result_df['n_layers'] == n_layers]['acc'].max()
        result_acc_max = result_df.loc[(result_df['n_layers'] == n_layers) & (result_df['acc'] == acc_max)].sort_values(['model_size (MB)', 'model_params'])
        display(result_acc_max)



        # select best accuracy model (up to 20)
        result_acc_max = result_acc_max.iloc[:20]

        # move 20 lowest sized ckpts
        for ckpt in result_acc_max['ckpt']:
            if ckpt in os.listdir(ckpt_dir):
                os.makedirs(os.path.join(best_ckpt_dir, model), exist_ok=True)
                os.rename(os.path.join(ckpt_dir, ckpt), os.path.join(best_ckpt_dir, model, ckpt))
                print(f'> moved {ckpt}')
                

        assert len(result_df) == len(scripts), f'len(result_acc_max) != len(scripts) ({len(result_acc_max)} != {len(scripts)})'
        # make the scripts
        scripts_acc_max = f'''model_name="{model}"
dataset_name="{data_name}"
tslib_dir="/data/yoom618/TSLib"
gpu_id=0

data_dir="${{tslib_dir}}/dataset"
checkpoint_dir="${{tslib_dir}}/checkpoints_best/${{model_name}}"'''
        if len(result_acc_max) > 1:
            scripts_acc_max += '\n\n# below all have the same performance'

        for idx in result_acc_max.index:
            scripts_acc_max += '''\n\npython run.py \\
--use_gpu True \\
--gpu_type cuda \\
--gpu ${gpu_id} \\
--task_name classification \\
--data UEA \\
--root_path "${data_dir}/${dataset_name}" \\
--checkpoints ${checkpoint_dir} \\
--model ${model_name} \\
--model_id "CLS_${dataset_name}" \\
'''
            scripts_acc_max += '\n'.join(scripts[idx].replace("--is_training 1", "--is_training 0").split('\n')[15:])
        scripts_acc_max = scripts_acc_max.strip()
        out_dir = os.path.join(best_script_dir, model)
        script_fname = f'{out_dir}/{data_name}_nlayers{n_layers}.sh'
        if not os.path.exists(script_fname):
            os.makedirs(out_dir, exist_ok=True)
            with open(script_fname, 'w') as file:
                file.write(scripts_acc_max)
            print(f'> saved {data_name}_nlayers{n_layers}.sh')
            print()

===================MambaML===================
EthanolConcentration

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
184,el2,dm512,ds8,expand1,dc4,nk36,tvdt0,tvB0,tvC0,useD0,gating4multilayer,0,0.410646,1699848,16.26,classification_CLS_EthanolConcentration_MambaM...,2

FaceDetection

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
142,el2,dm256,ds4,expand1,dc4,nk3,tvdt1,tvB1,tvC0,useD0,gating4multilayer,0,0.687855,533000,6.93,classification_CLS_FaceDetection_MambaMultiLay...,2
234,el2,dm1024,ds16,expand1,dc4,nk3,tvdt0,tvB1,tvC0,useD0,gating4multilayer,0,0.687855,6989832,46.20,classification_CLS_FaceDetection_MambaMultiLay...,2

Handwriting

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
196,el2,dm512,ds16,expand1,dc4,nk4,tvdt1,tvB0,tvC0,useD0,gating4multilayer,0,0.657647,1719304,16.33,classification_CLS_Handwriting_MambaMultiLayer...,2

Heartbeat

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
64,el2,dm64,ds8,expand1,dc4,nk9,tvdt0,tvB0,tvC0,useD0,gating4multilayer,0,0.804878,64968,1.48,classification_CLS_Heartbeat_MambaMultiLayer_U...,2
105,el2,dm128,ds8,expand1,dc4,nk9,tvdt0,tvB0,tvC1,useD0,gating4multilayer,0,0.804878,180104,3.14,classification_CLS_Heartbeat_MambaMultiLayer_U...,2

JapaneseVowels

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
216,el2,dm1024,ds4,expand1,dc4,nk3,tvdt0,tvB0,tvC0,useD0,gating4multilayer,0,0.986486,6517768,44.4,classification_CLS_JapaneseVowels_MambaMultiLa...,2

PEMS-SF

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
42,el2,dm64,ds1,expand1,dc4,nk3,tvdt0,tvB1,tvC0,useD0,gating4multilayer,0,0.855491,212360,2.04,classification_CLS_PEMS-SF_MambaMultiLayer_UEA...,2

SelfRegulationSCP1

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
96,el2,dm128,ds4,expand1,dc4,nk18,tvdt0,tvB0,tvC0,useD0,gating4multilayer,0,0.921502,120584,2.91,classification_CLS_SelfRegulationSCP1_MambaMul...,2
214,el2,dm1024,ds2,expand1,dc4,nk18,tvdt1,tvB1,tvC0,useD0,gating4multilayer,0,0.921502,6703112,45.11,classification_CLS_SelfRegulationSCP1_MambaMul...,2

SelfRegulationSCP2

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
194,el2,dm512,ds16,expand1,dc4,nk24,tvdt0,tvB1,tvC0,useD0,gating4multilayer,0,0.627778,1754120,16.47,classification_CLS_SelfRegulationSCP2_MambaMul...,2

SpokenArabicDigits

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
82,el2,dm128,ds1,expand1,dc4,nk3,tvdt0,tvB1,tvC0,useD0,gating4multilayer,0,0.998636,110472,2.87,classification_CLS_SpokenArabicDigits_MambaMul...,2
203,el2,dm1024,ds1,expand1,dc4,nk3,tvdt0,tvB1,tvC1,useD0,gating4multilayer,0,0.998636,6503432,44.35,classification_CLS_SpokenArabicDigits_MambaMul...,2
225,el2,dm1024,ds8,expand1,dc4,nk3,tvdt0,tvB0,tvC1,useD0,gating4multilayer,0,0.998636,6546440,44.51,classification_CLS_SpokenArabicDigits_MambaMul...,2

UWaveGestureLibrary

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
185,el2,dm512,ds8,expand1,dc4,nk7,tvdt0,tvB0,tvC1,useD0,gating4multilayer,0,0.934375,1657352,16.10,classification_CLS_UWaveGestureLibrary_MambaMu...,2
197,el2,dm512,ds16,expand1,dc4,nk7,tvdt1,tvB0,tvC1,useD0,gating4multilayer,0,0.934375,1714696,16.32,classification_CLS_UWaveGestureLibrary_MambaMu...,2

ArticularyWordRecognition

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
43,el2,dm64,ds1,expand1,dc4,nk3,tvdt0,tvB1,tvC1,useD0,gating4multilayer,0,0.993333,30344,1.35,classification_CLS_ArticularyWordRecognition_M...,2
133,el2,dm256,ds2,expand1,dc4,nk3,tvdt1,tvB0,tvC1,useD0,gating4multilayer,0,0.993333,432136,6.54,classification_CLS_ArticularyWordRecognition_M...,2
211,el2,dm1024,ds2,expand1,dc4,nk3,tvdt0,tvB1,tvC1,useD0,gating4multilayer,0,0.993333,6512648,44.38,classification_CLS_ArticularyWordRecognition_M...,2

AtrialFibrillation

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
4,el2,dm32,ds1,expand1,dc4,nk13,tvdt1,tvB0,tvC0,useD0,gating4multilayer,0,0.533333,8296,0.65,classification_CLS_AtrialFibrillation_MambaMul...,2
8,el2,dm32,ds2,expand1,dc4,nk13,tvdt0,tvB0,tvC0,useD0,gating4multilayer,0,0.533333,8360,0.65,classification_CLS_AtrialFibrillation_MambaMul...,2
9,el2,dm32,ds2,expand1,dc4,nk13,tvdt0,tvB0,tvC1,useD0,gating4multilayer,0,0.533333,8360,0.65,classification_CLS_AtrialFibrillation_MambaMul...,2
38,el2,dm32,ds16,expand1,dc4,nk13,tvdt1,tvB1,tvC0,useD0,gating4multilayer,0,0.533333,11176,0.66,classification_CLS_AtrialFibrillation_MambaMul...,2
54,el2,dm64,ds2,expand1,dc4,nk13,tvdt1,tvB1,tvC0,useD0,gating4multilayer,0,0.533333,29768,1.34,classification_CLS_AtrialFibrillation_MambaMul...,2
55,el2,dm64,ds2,expand1,dc4,nk13,tvdt1,tvB1,tvC1,useD0,gating4multilayer,0,0.533333,29768,1.34,classification_CLS_AtrialFibrillation_MambaMul...,2
60,el2,dm64,ds4,expand1,dc4,nk13,tvdt1,tvB0,tvC0,useD0,gating4multilayer,0,0.533333,30536,1.35,classification_CLS_AtrialFibrillation_MambaMul...,2
91,el2,dm128,ds2,expand1,dc4,nk13,tvdt0,tvB1,tvC1,useD0,gating4multilayer,0,0.533333,108680,2.86,classification_CLS_AtrialFibrillation_MambaMul...,2
90,el2,dm128,ds2,expand1,dc4,nk13,tvdt0,tvB1,tvC0,useD0,gating4multilayer,0,0.533333,108680,2.87,classification_CLS_AtrialFibrillation_MambaMul...,2
96,el2,dm128,ds4,expand1,dc4,nk13,tvdt0,tvB0,tvC0,useD0,gating4multilayer,0,0.533333,110216,2.87,classification_CLS_AtrialFibrillation_MambaMul...,2
113,el2,dm128,ds16,expand1,dc4,nk13,tvdt0,tvB0,tvC1,useD0,gating4multilayer,0,0.533333,119432,2.91,classification_CLS_AtrialFibrillation_MambaMul...,2
131,el2,dm256,ds2,expand1,dc4,nk13,tvdt0,tvB1,tvC1,useD0,gating4multilayer,0,0.533333,418056,6.49,classification_CLS_AtrialFibrillation_MambaMul...,2
159,el2,dm256,ds16,expand1,dc4,nk13,tvdt1,tvB1,tvC1,useD0,gating4multilayer,0,0.533333,447752,6.60,classification_CLS_AtrialFibrillation_MambaMul...,2
164,el2,dm512,ds1,expand1,dc4,nk13,tvdt1,tvB0,tvC0,useD0,gating4multilayer,0,0.533333,1668616,16.14,classification_CLS_AtrialFibrillation_MambaMul...,2
165,el2,dm512,ds1,expand1,dc4,nk13,tvdt1,tvB0,tvC1,useD0,gating4multilayer,0,0.533333,1668616,16.14,classification_CLS_AtrialFibrillation_MambaMul...,2
166,el2,dm512,ds1,expand1,dc4,nk13,tvdt1,tvB1,tvC0,useD0,gating4multilayer,0,0.533333,1668616,16.14,classification_CLS_AtrialFibrillation_MambaMul...,2
181,el2,dm512,ds4,expand1,dc4,nk13,tvdt1,tvB0,tvC1,useD0,gating4multilayer,0,0.533333,1677832,16.18,classification_CLS_AtrialFibrillation_MambaMul...,2
191,el2,dm512,ds8,expand1,dc4,nk13,tvdt1,tvB1,tvC1,useD0,gating4multilayer,0,0.533333,1690120,16.22,classification_CLS_AtrialFibrillation_MambaMul...,2
225,el2,dm1024,ds8,expand1,dc4,nk13,tvdt0,tvB0,tvC1,useD0,gating4multilayer,0,0.533333,6525960,44.44,classification_CLS_AtrialFibrillation_MambaMul...,2
206,el2,dm1024,ds1,expand1,dc4,nk13,tvdt1,tvB1,tvC0,useD0,gating4multilayer,0,0.533333,6614024,44.77,classification_CLS_AtrialFibrillation_MambaMul...,2

BasicMotions

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
0,el2,dm32,ds1,expand1,dc4,nk3,tvdt0,tvB0,tvC0,useD0,gating4multilayer,0,1.0,7944,0.65,classification_CLS_BasicMotions_MambaMultiLaye...,2
4,el2,dm32,ds1,expand1,dc4,nk3,tvdt1,tvB0,tvC0,useD0,gating4multilayer,0,1.0,8072,0.65,classification_CLS_BasicMotions_MambaMultiLaye...,2
6,el2,dm32,ds1,expand1,dc4,nk3,tvdt1,tvB1,tvC0,useD0,gating4multilayer,0,1.0,8072,0.65,classification_CLS_BasicMotions_MambaMultiLaye...,2
7,el2,dm32,ds1,expand1,dc4,nk3,tvdt1,tvB1,tvC1,useD0,gating4multilayer,0,1.0,8072,0.65,classification_CLS_BasicMotions_MambaMultiLaye...,2
8,el2,dm32,ds2,expand1,dc4,nk3,tvdt0,tvB0,tvC0,useD0,gating4multilayer,0,1.0,8136,0.65,classification_CLS_BasicMotions_MambaMultiLaye...,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
231,el2,dm1024,ds8,expand1,dc4,nk3,tvdt1,tvB1,tvC1,useD0,gating4multilayer,0,1.0,6649864,44.91,classification_CLS_BasicMotions_MambaMultiLaye...,2
239,el2,dm1024,ds16,expand1,dc4,nk3,tvdt1,tvB1,tvC1,useD0,gating4multilayer,0,1.0,6699016,45.09,classification_CLS_BasicMotions_MambaMultiLaye...,2
236,el2,dm1024,ds16,expand1,dc4,nk3,tvdt1,tvB0,tvC0,useD0,gating4multilayer,0,1.0,6699016,45.10,classification_CLS_BasicMotions_MambaMultiLaye...,2
237,el2,dm1024,ds16,expand1,dc4,nk3,tvdt1,tvB0,tvC1,useD0,gating4multilayer,0,1.0,6699016,45.10,classification_CLS_BasicMotions_MambaMultiLaye...,2
238,el2,dm1024,ds16,expand1,dc4,nk3,tvdt1,tvB1,tvC0,useD0,gating4multilayer,0,1.0,6699016,45.10,classification_CLS_BasicMotions_MambaMultiLaye...,2

CharacterTrajectories

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
48,el2,dm64,ds2,expand1,dc4,nk4,tvdt0,tvB0,tvC0,useD0,gating4multilayer,0,0.996518,29448,1.34,classification_CLS_CharacterTrajectories_Mamba...,2
52,el2,dm64,ds2,expand1,dc4,nk4,tvdt1,tvB0,tvC0,useD0,gating4multilayer,0,0.996518,29960,1.34,classification_CLS_CharacterTrajectories_Mamba...,2
59,el2,dm64,ds4,expand1,dc4,nk4,tvdt0,tvB1,tvC1,useD0,gating4multilayer,0,0.996518,30216,1.34,classification_CLS_CharacterTrajectories_Mamba...,2
81,el2,dm128,ds1,expand1,dc4,nk4,tvdt0,tvB0,tvC1,useD0,gating4multilayer,0,0.996518,108296,2.86,classification_CLS_CharacterTrajectories_Mamba...,2
100,el2,dm128,ds4,expand1,dc4,nk4,tvdt1,tvB0,tvC0,useD0,gating4multilayer,0,0.996518,112648,2.88,classification_CLS_CharacterTrajectories_Mamba...,2
126,el2,dm256,ds1,expand1,dc4,nk4,tvdt1,tvB1,tvC0,useD0,gating4multilayer,0,0.996518,425480,6.52,classification_CLS_CharacterTrajectories_Mamba...,2
140,el2,dm256,ds4,expand1,dc4,nk4,tvdt1,tvB0,tvC0,useD0,gating4multilayer,0,0.996518,430088,6.53,classification_CLS_CharacterTrajectories_Mamba...,2

Cricket

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
0,el2,dm32,ds1,expand1,dc4,nk24,tvdt0,tvB0,tvC0,useD0,gating4multilayer,0,1.0,12232,0.67,classification_CLS_Cricket_MambaMultiLayer_UEA...,2
3,el2,dm32,ds1,expand1,dc4,nk24,tvdt0,tvB1,tvC1,useD0,gating4multilayer,0,1.0,12232,0.67,classification_CLS_Cricket_MambaMultiLayer_UEA...,2
4,el2,dm32,ds1,expand1,dc4,nk24,tvdt1,tvB0,tvC0,useD0,gating4multilayer,0,1.0,12360,0.67,classification_CLS_Cricket_MambaMultiLayer_UEA...,2
42,el2,dm64,ds1,expand1,dc4,nk24,tvdt0,tvB1,tvC0,useD0,gating4multilayer,0,1.0,37000,1.37,classification_CLS_Cricket_MambaMultiLayer_UEA...,2
43,el2,dm64,ds1,expand1,dc4,nk24,tvdt0,tvB1,tvC1,useD0,gating4multilayer,0,1.0,37000,1.37,classification_CLS_Cricket_MambaMultiLayer_UEA...,2
58,el2,dm64,ds4,expand1,dc4,nk24,tvdt0,tvB1,tvC0,useD0,gating4multilayer,0,1.0,38152,1.38,classification_CLS_Cricket_MambaMultiLayer_UEA...,2
63,el2,dm64,ds4,expand1,dc4,nk24,tvdt1,tvB1,tvC1,useD0,gating4multilayer,0,1.0,38664,1.38,classification_CLS_Cricket_MambaMultiLayer_UEA...,2
67,el2,dm64,ds8,expand1,dc4,nk24,tvdt0,tvB1,tvC1,useD0,gating4multilayer,0,1.0,39688,1.38,classification_CLS_Cricket_MambaMultiLayer_UEA...,2
83,el2,dm128,ds1,expand1,dc4,nk24,tvdt0,tvB1,tvC1,useD0,gating4multilayer,0,1.0,124168,2.92,classification_CLS_Cricket_MambaMultiLayer_UEA...,2
90,el2,dm128,ds2,expand1,dc4,nk24,tvdt0,tvB1,tvC0,useD0,gating4multilayer,0,1.0,124936,2.93,classification_CLS_Cricket_MambaMultiLayer_UEA...,2
91,el2,dm128,ds2,expand1,dc4,nk24,tvdt0,tvB1,tvC1,useD0,gating4multilayer,0,1.0,124936,2.93,classification_CLS_Cricket_MambaMultiLayer_UEA...,2
95,el2,dm128,ds2,expand1,dc4,nk24,tvdt1,tvB1,tvC1,useD0,gating4multilayer,0,1.0,126984,2.93,classification_CLS_Cricket_MambaMultiLayer_UEA...,2
93,el2,dm128,ds2,expand1,dc4,nk24,tvdt1,tvB0,tvC1,useD0,gating4multilayer,0,1.0,126984,2.94,classification_CLS_Cricket_MambaMultiLayer_UEA...,2
107,el2,dm128,ds8,expand1,dc4,nk24,tvdt0,tvB1,tvC1,useD0,gating4multilayer,0,1.0,129544,2.94,classification_CLS_Cricket_MambaMultiLayer_UEA...,2
119,el2,dm128,ds16,expand1,dc4,nk24,tvdt1,tvB1,tvC1,useD0,gating4multilayer,0,1.0,137736,2.98,classification_CLS_Cricket_MambaMultiLayer_UEA...,2
122,el2,dm256,ds1,expand1,dc4,nk24,tvdt0,tvB1,tvC0,useD0,gating4multilayer,0,1.0,449032,6.60,classification_CLS_Cricket_MambaMultiLayer_UEA...,2
123,el2,dm256,ds1,expand1,dc4,nk24,tvdt0,tvB1,tvC1,useD0,gating4multilayer,0,1.0,449032,6.60,classification_CLS_Cricket_MambaMultiLayer_UEA...,2
124,el2,dm256,ds1,expand1,dc4,nk24,tvdt1,tvB0,tvC0,useD0,gating4multilayer,0,1.0,457224,6.64,classification_CLS_Cricket_MambaMultiLayer_UEA...,2
127,el2,dm256,ds1,expand1,dc4,nk24,tvdt1,tvB1,tvC1,useD0,gating4multilayer,0,1.0,457224,6.64,classification_CLS_Cricket_MambaMultiLayer_UEA...,2
132,el2,dm256,ds2,expand1,dc4,nk24,tvdt1,tvB0,tvC0,useD0,gating4multilayer,0,1.0,458760,6.64,classification_CLS_Cricket_MambaMultiLayer_UEA...,2
135,el2,dm256,ds2,expand1,dc4,nk24,tvdt1,tvB1,tvC1,useD0,gating4multilayer,0,1.0,458760,6.64,classification_CLS_Cricket_MambaMultiLayer_UEA...,2
146,el2,dm256,ds8,expand1,dc4,nk24,tvdt0,tvB1,tvC0,useD0,gating4multilayer,0,1.0,459784,6.65,classification_CLS_Cricket_MambaMultiLayer_UEA...,2
162,el2,dm512,ds1,expand1,dc4,nk24,tvdt0,tvB1,tvC0,useD0,gating4multilayer,0,1.0,1700872,16.26,classification_CLS_Cricket_MambaMultiLayer_UEA...,2
187,el2,dm512,ds8,expand1,dc4,nk24,tvdt0,tvB1,tvC1,useD0,gating4multilayer,0,1.0,1722376,16.34,classification_CLS_Cricket_MambaMultiLayer_UEA...,2
211,el2,dm1024,ds2,expand1,dc4,nk24,tvdt0,tvB1,tvC1,useD0,gating4multilayer,0,1.0,6619144,44.79,classification_CLS_Cricket_MambaMultiLayer_UEA...,2

DuckDuckGeese

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
224,el2,dm1024,ds8,expand1,dc4,nk6,tvdt0,tvB0,tvC0,useD0,gating4multilayer,0,0.7,14765064,75.86,classification_CLS_DuckDuckGeese_MambaMultiLay...,2

EigenWorms

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
31,el2,dm32,ds8,expand1,dc4,nk360,tvdt1,tvB1,tvC1,useD0,gating4multilayer,0,0.832061,77992,2.5,classification_CLS_EigenWorms_MambaMultiLayer_...,2

Epilepsy

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
219,el2,dm1024,ds4,expand1,dc4,nk5,tvdt0,tvB1,tvC1,useD0,gating4multilayer,0,0.978261,6491144,44.3,classification_CLS_Epilepsy_MambaMultiLayer_UE...,2

ERing

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
187,el2,dm512,ds8,expand1,dc4,nk3,tvdt0,tvB1,tvC1,useD0,gating4multilayer,0,0.951852,1651720,16.08,classification_CLS_ERing_MambaMultiLayer_UEA_f...,2

FingerMovements

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
67,el2,dm64,ds8,expand1,dc4,nk3,tvdt0,tvB1,tvC1,useD0,gating4multilayer,0,0.67,35208,1.36,classification_CLS_FingerMovements_MambaMultiL...,2

HandMovementDirection

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
132,el2,dm256,ds2,expand1,dc4,nk8,tvdt1,tvB0,tvC0,useD0,gating4multilayer,0,0.689189,440328,6.57,classification_CLS_HandMovementDirection_Mamba...,2

InsectWingbeat

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
168,el2,dm512,ds2,expand1,dc4,nk3,tvdt0,tvB0,tvC0,useD0,gating4multilayer,0,0.66104,1936392,17.16,classification_CLS_InsectWingbeat_MambaMultiLa...,2

> saved InsectWingbeat_nlayers2.sh

Libras

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
231,el2,dm1024,ds8,expand1,dc4,nk3,tvdt1,tvB1,tvC1,useD0,gating4multilayer,0,0.911111,6648840,44.9,classification_CLS_Libras_MambaMultiLayer_UEA_...,2

LSST

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
70,el2,dm64,ds8,expand1,dc4,nk3,tvdt1,tvB1,tvC0,useD0,gating4multilayer,0,0.440389,32264,1.35,classification_CLS_LSST_MambaMultiLayer_UEA_ft...,2

MotorImagery

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
127,el2,dm256,ds1,expand1,dc4,nk60,tvdt1,tvB1,tvC1,useD0,gating4multilayer,0,0.67,1400840,10.24,classification_CLS_MotorImagery_MambaMultiLaye...,2

NATOPS

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
217,el2,dm1024,ds4,expand1,dc4,nk3,tvdt0,tvB0,tvC1,useD0,gating4multilayer,0,0.988889,6551560,44.53,classification_CLS_NATOPS_MambaMultiLayer_UEA_...,2

PenDigits

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
23,el2,dm32,ds4,expand1,dc4,nk3,tvdt1,tvB1,tvC1,useD0,gating4multilayer,0,0.99171,8456,0.65,classification_CLS_PenDigits_MambaMultiLayer_U...,2

PhonemeSpectra

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
199,el2,dm1024,ds16,expand1,dc4,nk5,tvdt0,tvB1,tvC1,useD0,gating4multilayer,0,0.314345,6641672,44.88,classification_CLS_PhonemeSpectra_MambaMultiLa...,2

RacketSports

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
201,el2,dm1024,ds1,expand1,dc4,nk3,tvdt0,tvB0,tvC1,useD0,gating4multilayer,0,0.934211,6475784,44.24,classification_CLS_RacketSports_MambaMultiLaye...,2
225,el2,dm1024,ds8,expand1,dc4,nk3,tvdt0,tvB0,tvC1,useD0,gating4multilayer,0,0.934211,6518792,44.41,classification_CLS_RacketSports_MambaMultiLaye...,2

StandWalkJump

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
7,el2,dm32,ds1,expand1,dc4,nk50,tvdt1,tvB1,tvC1,useD0,gating4multilayer,0,0.666667,13864,0.67,classification_CLS_StandWalkJump_MambaMultiLay...,2
63,el2,dm64,ds4,expand1,dc4,nk50,tvdt1,tvB1,tvC1,useD0,gating4multilayer,0,0.666667,41672,1.39,classification_CLS_StandWalkJump_MambaMultiLay...,2
99,el2,dm128,ds4,expand1,dc4,nk50,tvdt0,tvB1,tvC1,useD0,gating4multilayer,0,0.666667,132488,2.96,classification_CLS_StandWalkJump_MambaMultiLay...,2

===================MambaML===================
EthanolConcentration

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
424,el3,dm512,ds8,expand1,dc4,nk36,tvdt0,tvB0,tvC0,useD0,gating4multilayer,0,0.418251,2519048,19.39,classification_CLS_EthanolConcentration_MambaM...,3

FaceDetection

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
424,el3,dm512,ds8,expand1,dc4,nk3,tvdt0,tvB0,tvC0,useD0,gating4multilayer,0,0.690976,2683912,20.02,classification_CLS_FaceDetection_MambaMultiLay...,3

Handwriting

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
424,el3,dm512,ds8,expand1,dc4,nk4,tvdt0,tvB0,tvC0,useD0,gating4multilayer,0,0.663529,2481160,19.24,classification_CLS_Handwriting_MambaMultiLayer...,3
432,el3,dm512,ds16,expand1,dc4,nk4,tvdt0,tvB0,tvC0,useD0,gating4multilayer,0,0.663529,2518024,19.38,classification_CLS_Handwriting_MambaMultiLayer...,3

Heartbeat

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
349,el3,dm128,ds8,expand1,dc4,nk9,tvdt1,tvB0,tvC1,useD0,gating4multilayer,0,0.804878,237448,3.36,classification_CLS_Heartbeat_MambaMultiLayer_U...,3
393,el3,dm256,ds16,expand1,dc4,nk9,tvdt0,tvB0,tvC1,useD0,gating4multilayer,0,0.804878,788232,7.90,classification_CLS_Heartbeat_MambaMultiLayer_U...,3

JapaneseVowels

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
362,el3,dm256,ds1,expand1,dc4,nk3,tvdt0,tvB1,tvC0,useD0,gating4multilayer,0,0.983784,624136,7.28,classification_CLS_JapaneseVowels_MambaMultiLa...,3

PEMS-SF

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
242,el3,dm32,ds1,expand1,dc4,nk3,tvdt0,tvB1,tvC0,useD0,gating4multilayer,0,0.867052,103400,1.02,classification_CLS_PEMS-SF_MambaMultiLayer_UEA...,3
281,el3,dm64,ds1,expand1,dc4,nk3,tvdt0,tvB0,tvC1,useD0,gating4multilayer,0,0.867052,225608,2.09,classification_CLS_PEMS-SF_MambaMultiLayer_UEA...,3

SelfRegulationSCP1

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
244,el3,dm32,ds1,expand1,dc4,nk18,tvdt1,tvB0,tvC0,useD0,gating4multilayer,0,0.911263,14440,0.68,classification_CLS_SelfRegulationSCP1_MambaMul...,3
384,el3,dm256,ds8,expand1,dc4,nk18,tvdt0,tvB0,tvC0,useD0,gating4multilayer,0,0.911263,656904,7.40,classification_CLS_SelfRegulationSCP1_MambaMul...,3
390,el3,dm256,ds8,expand1,dc4,nk18,tvdt1,tvB1,tvC0,useD0,gating4multilayer,0,0.911263,669192,7.45,classification_CLS_SelfRegulationSCP1_MambaMul...,3
397,el3,dm256,ds16,expand1,dc4,nk18,tvdt1,tvB0,tvC1,useD0,gating4multilayer,0,0.911263,687624,7.52,classification_CLS_SelfRegulationSCP1_MambaMul...,3
449,el3,dm1024,ds2,expand1,dc4,nk18,tvdt0,tvB0,tvC1,useD0,gating4multilayer,0,0.911263,9797640,56.92,classification_CLS_SelfRegulationSCP1_MambaMul...,3

SelfRegulationSCP2

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
415,el3,dm512,ds2,expand1,dc4,nk24,tvdt1,tvB1,tvC1,useD0,gating4multilayer,0,0.622222,2570248,19.58,classification_CLS_SelfRegulationSCP2_MambaMul...,3

SpokenArabicDigits

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
418,el3,dm512,ds4,expand1,dc4,nk3,tvdt0,tvB1,tvC0,useD0,gating4multilayer,0,0.998636,2468360,19.19,classification_CLS_SpokenArabicDigits_MambaMul...,3

UWaveGestureLibrary

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
336,el3,dm128,ds4,expand1,dc4,nk7,tvdt0,tvB0,tvC0,useD0,gating4multilayer,0,0.93125,162952,3.08,classification_CLS_UWaveGestureLibrary_MambaMu...,3
396,el3,dm256,ds16,expand1,dc4,nk7,tvdt1,tvB0,tvC0,useD0,gating4multilayer,0,0.93125,666888,7.44,classification_CLS_UWaveGestureLibrary_MambaMu...,3
440,el3,dm1024,ds1,expand1,dc4,nk7,tvdt0,tvB0,tvC0,useD0,gating4multilayer,0,0.93125,9705480,56.57,classification_CLS_UWaveGestureLibrary_MambaMu...,3

ArticularyWordRecognition

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
339,el3,dm128,ds4,expand1,dc4,nk3,tvdt0,tvB1,tvC1,useD0,gating4multilayer,0,0.993333,165896,3.09,classification_CLS_ArticularyWordRecognition_M...,3
359,el3,dm128,ds16,expand1,dc4,nk3,tvdt1,tvB1,tvC1,useD0,gating4multilayer,0,0.993333,182792,3.15,classification_CLS_ArticularyWordRecognition_M...,3

AtrialFibrillation

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
287,el3,dm64,ds1,expand1,dc4,nk13,tvdt1,tvB1,tvC1,useD0,gating4multilayer,0,0.6,42888,1.40,classification_CLS_AtrialFibrillation_MambaMul...,3
360,el3,dm256,ds1,expand1,dc4,nk13,tvdt0,tvB0,tvC0,useD0,gating4multilayer,0,0.6,620040,7.26,classification_CLS_AtrialFibrillation_MambaMul...,3
374,el3,dm256,ds2,expand1,dc4,nk13,tvdt1,tvB1,tvC0,useD0,gating4multilayer,0,0.6,634632,7.32,classification_CLS_AtrialFibrillation_MambaMul...,3

BasicMotions

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
244,el3,dm32,ds1,expand1,dc4,nk3,tvdt1,tvB0,tvC0,useD0,gating4multilayer,0,1.0,11624,0.67,classification_CLS_BasicMotions_MambaMultiLaye...,3
251,el3,dm32,ds2,expand1,dc4,nk3,tvdt0,tvB1,tvC1,useD0,gating4multilayer,0,1.0,11720,0.67,classification_CLS_BasicMotions_MambaMultiLaye...,3
252,el3,dm32,ds2,expand1,dc4,nk3,tvdt1,tvB0,tvC0,useD0,gating4multilayer,0,1.0,11912,0.67,classification_CLS_BasicMotions_MambaMultiLaye...,3
253,el3,dm32,ds2,expand1,dc4,nk3,tvdt1,tvB0,tvC1,useD0,gating4multilayer,0,1.0,11912,0.67,classification_CLS_BasicMotions_MambaMultiLaye...,3
254,el3,dm32,ds2,expand1,dc4,nk3,tvdt1,tvB1,tvC0,useD0,gating4multilayer,0,1.0,11912,0.67,classification_CLS_BasicMotions_MambaMultiLaye...,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
471,el3,dm1024,ds8,expand1,dc4,nk3,tvdt1,tvB1,tvC1,useD0,gating4multilayer,0,1.0,9959432,57.54,classification_CLS_BasicMotions_MambaMultiLaye...,3
476,el3,dm1024,ds16,expand1,dc4,nk3,tvdt1,tvB0,tvC0,useD0,gating4multilayer,0,1.0,10033160,57.82,classification_CLS_BasicMotions_MambaMultiLaye...,3
477,el3,dm1024,ds16,expand1,dc4,nk3,tvdt1,tvB0,tvC1,useD0,gating4multilayer,0,1.0,10033160,57.82,classification_CLS_BasicMotions_MambaMultiLaye...,3
478,el3,dm1024,ds16,expand1,dc4,nk3,tvdt1,tvB1,tvC0,useD0,gating4multilayer,0,1.0,10033160,57.82,classification_CLS_BasicMotions_MambaMultiLaye...,3
479,el3,dm1024,ds16,expand1,dc4,nk3,tvdt1,tvB1,tvC1,useD0,gating4multilayer,0,1.0,10033160,57.82,classification_CLS_BasicMotions_MambaMultiLaye...,3

CharacterTrajectories

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
293,el3,dm64,ds2,expand1,dc4,nk4,tvdt1,tvB0,tvC1,useD0,gating4multilayer,0,0.997214,43656,1.4,classification_CLS_CharacterTrajectories_Mamba...,3

Cricket

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
244,el3,dm32,ds1,expand1,dc4,nk24,tvdt1,tvB0,tvC0,useD0,gating4multilayer,0,1.0,15912,0.68,classification_CLS_Cricket_MambaMultiLayer_UEA...,3
248,el3,dm32,ds2,expand1,dc4,nk24,tvdt0,tvB0,tvC0,useD0,gating4multilayer,0,1.0,16008,0.68,classification_CLS_Cricket_MambaMultiLayer_UEA...,3
254,el3,dm32,ds2,expand1,dc4,nk24,tvdt1,tvB1,tvC0,useD0,gating4multilayer,0,1.0,16200,0.68,classification_CLS_Cricket_MambaMultiLayer_UEA...,3
252,el3,dm32,ds2,expand1,dc4,nk24,tvdt1,tvB0,tvC0,useD0,gating4multilayer,0,1.0,16200,0.69,classification_CLS_Cricket_MambaMultiLayer_UEA...,3
260,el3,dm32,ds4,expand1,dc4,nk24,tvdt1,tvB0,tvC0,useD0,gating4multilayer,0,1.0,16776,0.69,classification_CLS_Cricket_MambaMultiLayer_UEA...,3
262,el3,dm32,ds4,expand1,dc4,nk24,tvdt1,tvB1,tvC0,useD0,gating4multilayer,0,1.0,16776,0.69,classification_CLS_Cricket_MambaMultiLayer_UEA...,3
275,el3,dm32,ds16,expand1,dc4,nk24,tvdt0,tvB1,tvC1,useD0,gating4multilayer,0,1.0,20040,0.70,classification_CLS_Cricket_MambaMultiLayer_UEA...,3
282,el3,dm64,ds1,expand1,dc4,nk24,tvdt0,tvB1,tvC0,useD0,gating4multilayer,0,1.0,50248,1.43,classification_CLS_Cricket_MambaMultiLayer_UEA...,3
291,el3,dm64,ds2,expand1,dc4,nk24,tvdt0,tvB1,tvC1,useD0,gating4multilayer,0,1.0,50824,1.43,classification_CLS_Cricket_MambaMultiLayer_UEA...,3
293,el3,dm64,ds2,expand1,dc4,nk24,tvdt1,tvB0,tvC1,useD0,gating4multilayer,0,1.0,51592,1.43,classification_CLS_Cricket_MambaMultiLayer_UEA...,3
313,el3,dm64,ds16,expand1,dc4,nk24,tvdt0,tvB0,tvC1,useD0,gating4multilayer,0,1.0,58888,1.46,classification_CLS_Cricket_MambaMultiLayer_UEA...,3
331,el3,dm128,ds2,expand1,dc4,nk24,tvdt0,tvB1,tvC1,useD0,gating4multilayer,0,1.0,176904,3.13,classification_CLS_Cricket_MambaMultiLayer_UEA...,3
327,el3,dm128,ds1,expand1,dc4,nk24,tvdt1,tvB1,tvC1,useD0,gating4multilayer,0,1.0,178824,3.14,classification_CLS_Cricket_MambaMultiLayer_UEA...,3
334,el3,dm128,ds2,expand1,dc4,nk24,tvdt1,tvB1,tvC0,useD0,gating4multilayer,0,1.0,179976,3.14,classification_CLS_Cricket_MambaMultiLayer_UEA...,3
353,el3,dm128,ds16,expand1,dc4,nk24,tvdt0,tvB0,tvC1,useD0,gating4multilayer,0,1.0,193032,3.19,classification_CLS_Cricket_MambaMultiLayer_UEA...,3
354,el3,dm128,ds16,expand1,dc4,nk24,tvdt0,tvB1,tvC0,useD0,gating4multilayer,0,1.0,193032,3.19,classification_CLS_Cricket_MambaMultiLayer_UEA...,3
358,el3,dm128,ds16,expand1,dc4,nk24,tvdt1,tvB1,tvC0,useD0,gating4multilayer,0,1.0,196104,3.20,classification_CLS_Cricket_MambaMultiLayer_UEA...,3
369,el3,dm256,ds2,expand1,dc4,nk24,tvdt0,tvB0,tvC1,useD0,gating4multilayer,0,1.0,654856,7.39,classification_CLS_Cricket_MambaMultiLayer_UEA...,3
367,el3,dm256,ds1,expand1,dc4,nk24,tvdt1,tvB1,tvC1,useD0,gating4multilayer,0,1.0,664840,7.43,classification_CLS_Cricket_MambaMultiLayer_UEA...,3
385,el3,dm256,ds8,expand1,dc4,nk24,tvdt0,tvB0,tvC1,useD0,gating4multilayer,0,1.0,668680,7.45,classification_CLS_Cricket_MambaMultiLayer_UEA...,3
382,el3,dm256,ds4,expand1,dc4,nk24,tvdt1,tvB1,tvC0,useD0,gating4multilayer,0,1.0,671752,7.46,classification_CLS_Cricket_MambaMultiLayer_UEA...,3
391,el3,dm256,ds8,expand1,dc4,nk24,tvdt1,tvB1,tvC1,useD0,gating4multilayer,0,1.0,680968,7.49,classification_CLS_Cricket_MambaMultiLayer_UEA...,3
402,el3,dm512,ds1,expand1,dc4,nk24,tvdt0,tvB1,tvC0,useD0,gating4multilayer,0,1.0,2509320,19.35,classification_CLS_Cricket_MambaMultiLayer_UEA...,3
407,el3,dm512,ds1,expand1,dc4,nk24,tvdt1,tvB1,tvC1,useD0,gating4multilayer,0,1.0,2558472,19.54,classification_CLS_Cricket_MambaMultiLayer_UEA...,3
431,el3,dm512,ds8,expand1,dc4,nk24,tvdt1,tvB1,tvC1,useD0,gating4multilayer,0,1.0,2590728,19.66,classification_CLS_Cricket_MambaMultiLayer_UEA...,3
441,el3,dm1024,ds1,expand1,dc4,nk24,tvdt0,tvB0,tvC1,useD0,gating4multilayer,0,1.0,9835528,57.06,classification_CLS_Cricket_MambaMultiLayer_UEA...,3
451,el3,dm1024,ds2,expand1,dc4,nk24,tvdt0,tvB1,tvC1,useD0,gating4multilayer,0,1.0,9844744,57.10,classification_CLS_Cricket_MambaMultiLayer_UEA...,3
456,el3,dm1024,ds4,expand1,dc4,nk24,tvdt0,tvB0,tvC0,useD0,gating4multilayer,0,1.0,9863176,57.17,classification_CLS_Cricket_MambaMultiLayer_UEA...,3
472,el3,dm1024,ds16,expand1,dc4,nk24,tvdt0,tvB0,tvC0,useD0,gating4multilayer,0,1.0,9973768,57.59,classification_CLS_Cricket_MambaMultiLayer_UEA...,3
473,el3,dm1024,ds16,expand1,dc4,nk24,tvdt0,tvB0,tvC1,useD0,gating4multilayer,0,1.0,9973768,57.59,classification_CLS_Cricket_MambaMultiLayer_UEA...,3
445,el3,dm1024,ds1,expand1,dc4,nk24,tvdt1,tvB0,tvC1,useD0,gating4multilayer,0,1.0,10032136,57.81,classification_CLS_Cricket_MambaMultiLayer_UEA...,3
447,el3,dm1024,ds1,expand1,dc4,nk24,tvdt1,tvB1,tvC1,useD0,gating4multilayer,0,1.0,10032136,57.81,classification_CLS_Cricket_MambaMultiLayer_UEA...,3
453,el3,dm1024,ds2,expand1,dc4,nk24,tvdt1,tvB0,tvC1,useD0,gating4multilayer,0,1.0,10041352,57.85,classification_CLS_Cricket_MambaMultiLayer_UEA...,3
478,el3,dm1024,ds16,expand1,dc4,nk24,tvdt1,tvB1,tvC0,useD0,gating4multilayer,0,1.0,10170376,58.34,classification_CLS_Cricket_MambaMultiLayer_UEA...,3

DuckDuckGeese

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
287,el3,dm64,ds1,expand1,dc4,nk6,tvdt1,tvB1,tvC1,useD0,gating4multilayer,0,0.68,557832,3.36,classification_CLS_DuckDuckGeese_MambaMultiLay...,3
297,el3,dm64,ds4,expand1,dc4,nk6,tvdt0,tvB0,tvC1,useD0,gating4multilayer,0,0.68,558792,3.37,classification_CLS_DuckDuckGeese_MambaMultiLay...,3
304,el3,dm64,ds8,expand1,dc4,nk6,tvdt0,tvB0,tvC0,useD0,gating4multilayer,0,0.68,561096,3.37,classification_CLS_DuckDuckGeese_MambaMultiLay...,3
332,el3,dm128,ds2,expand1,dc4,nk6,tvdt1,tvB0,tvC0,useD0,gating4multilayer,0,0.68,1193608,7.01,classification_CLS_DuckDuckGeese_MambaMultiLay...,3
440,el3,dm1024,ds1,expand1,dc4,nk6,tvdt0,tvB0,tvC0,useD0,gating4multilayer,0,0.68,17944584,88.00,classification_CLS_DuckDuckGeese_MambaMultiLay...,3
451,el3,dm1024,ds2,expand1,dc4,nk6,tvdt0,tvB1,tvC1,useD0,gating4multilayer,0,0.68,17953800,88.03,classification_CLS_DuckDuckGeese_MambaMultiLay...,3
460,el3,dm1024,ds4,expand1,dc4,nk6,tvdt1,tvB0,tvC0,useD0,gating4multilayer,0,0.68,18168840,88.85,classification_CLS_DuckDuckGeese_MambaMultiLay...,3
478,el3,dm1024,ds16,expand1,dc4,nk6,tvdt1,tvB1,tvC0,useD0,gating4multilayer,0,0.68,18279432,89.27,classification_CLS_DuckDuckGeese_MambaMultiLay...,3

EigenWorms

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
434,el3,dm512,ds16,expand1,dc4,nk360,tvdt0,tvB1,tvC0,useD0,gating4multilayer,0,0.854962,3607048,48.9,classification_CLS_EigenWorms_MambaMultiLayer_...,3

Epilepsy

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
286,el3,dm64,ds1,expand1,dc4,nk5,tvdt1,tvB1,tvC0,useD0,gating4multilayer,0,0.971014,42248,1.39,classification_CLS_Epilepsy_MambaMultiLayer_UE...,3
349,el3,dm128,ds8,expand1,dc4,nk5,tvdt1,tvB0,tvC1,useD0,gating4multilayer,0,0.971014,169352,3.10,classification_CLS_Epilepsy_MambaMultiLayer_UE...,3
361,el3,dm256,ds1,expand1,dc4,nk5,tvdt0,tvB0,tvC1,useD0,gating4multilayer,0,0.971014,617480,7.25,classification_CLS_Epilepsy_MambaMultiLayer_UE...,3
375,el3,dm256,ds2,expand1,dc4,nk5,tvdt1,tvB1,tvC1,useD0,gating4multilayer,0,0.971014,632072,7.31,classification_CLS_Epilepsy_MambaMultiLayer_UE...,3
381,el3,dm256,ds4,expand1,dc4,nk5,tvdt1,tvB0,tvC1,useD0,gating4multilayer,0,0.971014,636680,7.32,classification_CLS_Epilepsy_MambaMultiLayer_UE...,3
422,el3,dm512,ds4,expand1,dc4,nk5,tvdt1,tvB1,tvC0,useD0,gating4multilayer,0,0.971014,2502152,19.32,classification_CLS_Epilepsy_MambaMultiLayer_UE...,3
438,el3,dm512,ds16,expand1,dc4,nk5,tvdt1,tvB1,tvC0,useD0,gating4multilayer,0,0.971014,2557448,19.53,classification_CLS_Epilepsy_MambaMultiLayer_UE...,3
442,el3,dm1024,ds1,expand1,dc4,nk5,tvdt0,tvB1,tvC0,useD0,gating4multilayer,0,0.971014,9695240,56.53,classification_CLS_Epilepsy_MambaMultiLayer_UE...,3
456,el3,dm1024,ds4,expand1,dc4,nk5,tvdt0,tvB0,tvC0,useD0,gating4multilayer,0,0.971014,9722888,56.63,classification_CLS_Epilepsy_MambaMultiLayer_UE...,3
444,el3,dm1024,ds1,expand1,dc4,nk5,tvdt1,tvB0,tvC0,useD0,gating4multilayer,0,0.971014,9891848,57.28,classification_CLS_Epilepsy_MambaMultiLayer_UE...,3
452,el3,dm1024,ds2,expand1,dc4,nk5,tvdt1,tvB0,tvC0,useD0,gating4multilayer,0,0.971014,9901064,57.31,classification_CLS_Epilepsy_MambaMultiLayer_UE...,3
462,el3,dm1024,ds4,expand1,dc4,nk5,tvdt1,tvB1,tvC0,useD0,gating4multilayer,0,0.971014,9919496,57.38,classification_CLS_Epilepsy_MambaMultiLayer_UE...,3
469,el3,dm1024,ds8,expand1,dc4,nk5,tvdt1,tvB0,tvC1,useD0,gating4multilayer,0,0.971014,9956360,57.52,classification_CLS_Epilepsy_MambaMultiLayer_UE...,3
479,el3,dm1024,ds16,expand1,dc4,nk5,tvdt1,tvB1,tvC1,useD0,gating4multilayer,0,0.971014,10030088,57.81,classification_CLS_Epilepsy_MambaMultiLayer_UE...,3

ERing

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
274,el3,dm32,ds16,expand1,dc4,nk3,tvdt0,tvB1,tvC0,useD0,gating4multilayer,0,0.940741,15624,0.68,classification_CLS_ERing_MambaMultiLayer_UEA_f...,3
401,el3,dm512,ds1,expand1,dc4,nk3,tvdt0,tvB0,tvC1,useD0,gating4multilayer,0,0.940741,2438664,19.08,classification_CLS_ERing_MambaMultiLayer_UEA_f...,3
436,el3,dm512,ds16,expand1,dc4,nk3,tvdt1,tvB0,tvC0,useD0,gating4multilayer,0,0.940741,2556936,19.53,classification_CLS_ERing_MambaMultiLayer_UEA_f...,3

FingerMovements

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
309,el3,dm64,ds8,expand1,dc4,nk3,tvdt1,tvB0,tvC1,useD0,gating4multilayer,0,0.65,50568,1.43,classification_CLS_FingerMovements_MambaMultiL...,3
447,el3,dm1024,ds1,expand1,dc4,nk3,tvdt1,tvB1,tvC1,useD0,gating4multilayer,0,0.65,9960456,57.54,classification_CLS_FingerMovements_MambaMultiL...,3

HandMovementDirection

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
392,el3,dm256,ds16,expand1,dc4,nk8,tvdt0,tvB0,tvC0,useD0,gating4multilayer,0,0.689189,668680,7.45,classification_CLS_HandMovementDirection_Mamba...,3

InsectWingbeat

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
384,el3,dm256,ds8,expand1,dc4,nk3,tvdt0,tvB0,tvC0,useD0,gating4multilayer,0,0.65596,784904,7.89,classification_CLS_InsectWingbeat_MambaMultiLa...,3

> moved classification_CLS_InsectWingbeat_MambaMultiLayer_UEA_ftM_sl22_ll0_pl0_el3_dm256_ds8_expand1_dc4_nk3_tvdt0_tvB0_tvC0_useD0_gating4multilayer_0
> saved InsectWingbeat_nlayers3.sh

Libras

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
318,el3,dm64,ds16,expand1,dc4,nk3,tvdt1,tvB1,tvC0,useD0,gating4multilayer,0,0.894444,51016,1.43,classification_CLS_Libras_MambaMultiLayer_UEA_...,3

LSST

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
283,el3,dm64,ds1,expand1,dc4,nk3,tvdt0,tvB1,tvC1,useD0,gating4multilayer,0,0.425385,42312,1.39,classification_CLS_LSST_MambaMultiLayer_UEA_ft...,3

MotorImagery

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
263,el3,dm32,ds4,expand1,dc4,nk60,tvdt1,tvB1,tvC1,useD0,gating4multilayer,0,0.66,134728,1.14,classification_CLS_MotorImagery_MambaMultiLaye...,3

NATOPS

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
413,el3,dm512,ds2,expand1,dc4,nk3,tvdt1,tvB0,tvC1,useD0,gating4multilayer,0,0.983333,2523144,19.4,classification_CLS_NATOPS_MambaMultiLayer_UEA_...,3

PenDigits

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
279,el3,dm32,ds16,expand1,dc4,nk3,tvdt1,tvB1,tvC1,useD0,gating4multilayer,0,0.991995,15752,0.68,classification_CLS_PenDigits_MambaMultiLayer_U...,3

PhonemeSpectra

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
391,el3,dm512,ds8,expand1,dc4,nk5,tvdt0,tvB1,tvC1,useD0,gating4multilayer,0,0.309872,2509832,19.35,classification_CLS_PhonemeSpectra_MambaMultiLa...,3

RacketSports

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
317,el3,dm64,ds16,expand1,dc4,nk3,tvdt1,tvB0,tvC1,useD0,gating4multilayer,0,0.927632,51080,1.43,classification_CLS_RacketSports_MambaMultiLaye...,3
465,el3,dm1024,ds8,expand1,dc4,nk3,tvdt0,tvB0,tvC1,useD0,gating4multilayer,0,0.927632,9762824,56.79,classification_CLS_RacketSports_MambaMultiLaye...,3

StandWalkJump

,9,10,11,12,13,14,15,16,17,18,19,20,acc,model_params,model_size (MB),ckpt,n_layers
335,el3,dm128,ds2,expand1,dc4,nk50,tvdt1,tvB1,tvC1,useD0,gating4multilayer,0,0.666667,185992,3.16,classification_CLS_StandWalkJump_MambaMultiLay...,3